racket/typed-racket

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/typecheck/provide-handling.rkt
typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt
typed-racket-lib/typed-racket/utils/redirect-contract.rkt

I'll squash this and write a real commit message once it works.
Which it doesn't yet.

Move contracted defns to a submodule.

---

typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-contracts.rkt
typed-racket-test/succeed/gh-issue-38.rkt

Use contract-neg-party to accurately handle contracted applications

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

Strengthen the types for member, memv, memq, and memf

---

typed-racket-lib/typed-racket/typecheck/tc-subst.rkt
typed-racket-lib/typed-racket/types/subtype.rkt
typed-racket-test/unit-tests/metafunction-tests.rkt
typed-racket-test/unit-tests/subtype-tests.rkt

This PR should fix the current test failures on DrDr.
This also includes a subtyping change that I needed to make for the tests to pass.

Fix type restriction in values->tc-results

---

typed-racket-lib/typed-racket/base-env/annotate-classes.rkt
typed-racket-lib/typed-racket/base-env/prims-struct.rkt
typed-racket-lib/typed-racket/base-env/prims.rkt
typed-racket-lib/typed-racket/base-env/top-interaction.rkt
typed-racket-lib/typed-racket/base-env/type-env-lang.rkt
typed-racket-lib/typed-racket/private/parse-classes.rkt
typed-racket-lib/typed-racket/private/syntax-properties.rkt
typed-racket-lib/typed-racket/typecheck/internal-forms.rkt
typed-racket-lib/typed-racket/typed-racket.rkt
typed-racket-lib/typed-racket/utils/literal-syntax-class.rkt
typed-racket-lib/typed-racket/utils/redirect-contract.rkt
typed-racket-lib/typed-racket/utils/tc-utils.rkt
typed-racket-lib/typed-racket/utils/utils.rkt

This is now implemented, and is roughly ready for review. Still to-do:

More dependency reduction.

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

see https://github.com/racket/scribble/pull/8#discussion_r33423152

make append preserve non-emptyness of first argument

---

typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl
typed-racket-lib/typed-racket/base-env/prims-struct.rkt
typed-racket-lib/typed-racket/base-env/prims.rkt
typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/typecheck/internal-forms.rkt
typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt
typed-racket-lib/typed-racket/types/abbrev.rkt
typed-racket-lib/typed-racket/types/printer.rkt
typed-racket-lib/typed-racket/types/subtype.rkt
typed-racket-test/fail/define-new-subtype.rkt
typed-racket-test/succeed/define-new-subtype.rkt

inspired by haskell newtypes
http://www.mail-archive.com/racket-users@googlegroups.com/msg27118.html
https://www.haskell.org/tutorial/moretypes.html

add newtypes

---

typed-racket-lib/typed-racket/base-env/base-types-extra.rkt
typed-racket-lib/typed-racket/base-env/prims-struct.rkt
typed-racket-lib/typed-racket/private/parse-type.rkt
typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt
typed-racket-lib/typed-racket/types/subtype.rkt
typed-racket-lib/typed/racket/base.rkt
typed-racket-test/fail/define-new-subtype.rkt
typed-racket-test/fail/issue-169-1.rkt
typed-racket-test/fail/issue-169-2.rkt
typed-racket-test/succeed/define-new-subtype-mu-rec.rkt

fix issue #169

---

typed-racket-lib/typed-racket/types/printer.rkt

A change like this probably would have saved me a lot of trouble debugging.

print more Error types as Error types

---

typed-racket-lib/typed-racket/rep/rep-utils.rkt
typed-racket-test/succeed/match-or.rkt

Fix compilation of `midi-readwrite`. Review by @stamourv requested.

Fix midi-readwrite.

---

typed-racket-lib/typed/racket/base.rkt
typed-racket-lib/typed/racket/unit.rkt

fixes https://github.com/racket/typed-racket/issues/234

Don't provide Unit from typed/racket/base

---

typed-racket-doc/typed-racket/scribblings/guide/typed-untyped-interaction.scrbl

p -> pt
(Thanks to Ben Chung for finding it.)

Fix typo in the docs.

---

typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt
typed-racket-test/succeed/provide-for-meta.rkt

Keep ignored provide forms in the output.

---

typed-racket-lib/typed-racket/rep/type-rep.rkt

scope structs are cute, but don't do anything useful.

removed scope structs from types

---

typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl
typed-racket-lib/typed-racket/base-env/prims-struct.rkt
typed-racket-lib/typed-racket/typecheck/internal-forms.rkt
typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt
typed-racket-test/fail/struct-extra-constructor.rkt
typed-racket-test/succeed/struct-options.rkt

Add support for #:constructor-name and #:extra-constructor-name to struct

---

typed-racket-lib/typed-racket/utils/any-wrap.rkt
typed-racket-lib/typed-racket/utils/evt-contract.rkt
typed-racket-lib/typed-racket/utils/opaque-object.rkt
typed-racket-lib/typed-racket/utils/sealing-contract.rkt
typed-racket-lib/typed-racket/utils/struct-type-c.rkt

I didn't try to run any test suites for this (well, I did make sure DrRacket starts up). I hear that creating the pull request triggers something to run the tests on this commit, so I'm looking forward to seeing that in action!

port typed-racket contract to late-neg projections

---

typed-racket-more/typed/racket/private/gui-types.rkt

fixup wrong type definition of (set-caret-owner), it needs (Instance Snip%).

Fixup wrong type definition: set-caret-owner, it needs (Instance Snip%)

---

typed-racket-compatibility/info.rkt
typed-racket-doc/info.rkt
typed-racket-doc/typed-racket/scribblings/reference/libraries.scrbl
typed-racket-lib/info.rkt
typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-more/info.rkt
typed-racket-more/typed/racket/random.rkt
typed-racket-test/info.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt
typed-racket/info.rkt

Should probably specify a package dependency on a newer "base".

Add typed/racket/random

---

typed-racket-test/unit-tests/typecheck-tests.rkt

For github issues #111 #113 #114 #115

regression tests for fl ops

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-more/typed/racket/fasl.rkt

1. add (path-replace-extension) and (path-add-extension);
2. allow setting names when making special ports;
3. (tcp-addresses) accepts Tcp-Listener;
4. add typed/racket/fasl.

Add some useful type definitions

---

typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-lib/typed-racket/types/overlap.rkt
typed-racket-lib/typed-racket/types/update.rkt

The bug in tc-struct.rkt has been there for a while but only occurs when TR contracts are on.
I think we should look into making the TR contracts a part of our automated Travis-CI testing.

fix contract related bugs

---

typed-racket-more/typed/syntax/modread.rkt
typed-racket-more/typed/syntax/readerr.rkt
typed-racket-more/typed/syntax/srcloc.rkt

Typed versions of syntax/modread, syntax/srcloc, and syntax/readerr.

Add typed/syntax/modread, typed/syntax/srcloc, and typed/syntax/readerr

---

typed-racket-lib/typed-racket/base-env/base-env.rkt

1. (call-with-atomic-output-file)
2. (filesystem-change-evt) with those in Section 15.2.4

Add filesystem related functions

---

typed-racket-lib/typed-racket/base-env/prims-contract.rkt
typed-racket-test/succeed/unsafe-require.rkt

This changes how the `#:opaque` option in `unsafe-require/typed` behaves. It changes the contract on the predicate to allow opaque structs to be passed as `Any` without displaying a warning.
This fixes an issue raise in https://groups.google.com/forum/#!topic/racket-users/-pgP7-C_3D4, so that it can work if you use `unsafe-require/typed`

unsafe-require/typed #:opaque doesn't warn about opaque structs passed as Any

---

typed-racket-lib/typed-racket/base-env/prims-contract.rkt
typed-racket-lib/typed-racket/base-env/prims-struct.rkt

Add missing source locations.

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

Extend type of vector->list.

---

typed-racket-lib/typed-racket/infer/intersect.rkt
typed-racket-test/succeed/intersect-no-intersections.rkt

These changes attempt to make computing type intersections a more commutative operation.

fix intersect, make it (hopefully) commutative

---

typed-racket-more/typed/racket/gui/base.rkt

It should return `(Option Positive-Real)`

improvement: (get-display-backing-scale)

---

typed-racket-doc/typed-racket/scribblings/reference/libraries.scrbl
typed-racket-more/typed/images/compile-time.rkt
typed-racket-test/succeed/pr476-compile-time-images.rkt

copied from `images/compile-time` with few modifications.

Add typed/images/compile-time.rkt

---

typed-racket-test/succeed/issue-33.rkt

regression test for issue #33

---

typed-racket-lib/typed-racket/types/subtype.rkt

caching was broken (nothing was ever cached) -- after fixing it, it provided no benefit to type checking times, so I removed the caching code.

remove broken subtype caching

---

typed-racket-lib/typed-racket/env/init-envs.rkt
typed-racket-test/unit-tests/init-env-tests.rkt

fixes https://github.com/racket/typed-racket/issues/515

fix serialization of objects

---

typed-racket-lib/typed-racket/base-env/base-env.rkt

see https://github.com/racket/racket/commit/e22a5da06c7517332c0276e903cb6f4c14105f0c

update find-relative-path type w/ new keyword

---

typed-racket-lib/typed-racket/rep/object-rep.rkt

fixes errors seen in http://drdr.racket-lang.org/39436/

fix some lexp function contracts

---

typed-racket-doc/typed-racket/scribblings/reference/experimental.scrbl
typed-racket-doc/typed-racket/scribblings/reference/types.scrbl

Moves the refinement and linear integer arithmetic docs addition to the experimental section of the docs for now.

move refine and linear integer stuff in docs

---

typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/types/printer.rkt
typed-racket-test/unit-tests/type-printer-tests.rkt

fix simple printing bug (see #545)

fix intersection printing err

---

typed-racket-lib/typed-racket/types/current-seen.rkt
typed-racket-lib/typed-racket/types/overlap.rkt
typed-racket-test/succeed/gh-issue-542.rkt

Fix overlap mask error

---

typed-racket-lib/typed-racket/typecheck/tc-expression.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

fixes https://github.com/racket/typed-racket/issues/561

erase object when inst is present

---

typed-racket-lib/typed-racket/types/generalize.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

fixes https://github.com/racket/typed-racket/issues/573

add generalize clauses for new hash types

---

typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-lambda.rkt
typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-list.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

Improve loop inference heuristics.

---

typed-racket-lib/typed-racket/typecheck/tc-app-helper.rkt

Currently the following program:
```racket
#lang typed/racket/base
(define x : Number 42)
(apply + x)
```
has this error message:
```
Type Checker: Bad arguments to function in `apply':
Domains: Number *
Arguments: Number *
in: (apply + x)
```
Which is awful, since the expected domains line and argument type line are _identical_.
This PR changes it to the following (i.e. it drops the `*` from the `Arguments` line):
```
temp.rkt:7:0: Type Checker: Bad arguments to function in `apply':
Domains: Number *
Arguments: Number
in: (apply + x)
```
Perhaps there is an even better way to display this? (not sure -- comments welcome)

fix domain printing, especially rest args

---

typed-racket-lib/typed-racket/infer/infer-unit.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

Problem reported by @schackbrian2012. Closes #608.

Handle subtyping with all-optional kw args better.

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

=) Adds the new keyword are for `check-duplicates` (see https://github.com/racket/racket/pull/1840)
=( Will break any programs using `inst` and `check-duplicates`

update check-duplicates with #:default kw arg

---

typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

add types for new numeric primitives

---

typed-racket-lib/typed-racket/private/parse-type.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

Fixes https://github.com/racket/typed-racket/issues/675.

fix dep fun precondition parsing

---

typed-racket-lib/typed-racket/typecheck/tc-funapp.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

fixes https://github.com/racket/typed-racket/issues/721

improve application of unions of functions

---

typed-racket-doc/typed-racket/scribblings/guide/caveats.scrbl

Adds some advice regarding using Typed Racket and match.
See https://github.com/racket/typed-racket/pull/759.

add notes about TR+match in docs

---

typed-racket-lib/typed-racket/typecheck/tc-app-helper.rkt

Fixes https://github.com/racket/typed-racket/issues/778

fix domain printing for rest args

---

typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-hetero.rkt
typed-racket-test/succeed/match-overlap-unsafe-struct-ref.rkt

Support `unsafe-struct-ref` on intersections.

---

typed-racket-lib/typed-racket/base-env/base-env.rkt

More specific type for `file-stream-port?` and `terminal-port?`.

More specific type for file-stream-port? and terminal-port?

---

typed-racket-test/succeed/issue-807.rkt

test: add regression test for issue #807

---

typed-racket-lib/typed-racket/optimizer/number.rkt

Fix optimizer for `(angle 0)`.

---

typed-racket-doc/typed-racket/scribblings/guide/caveats.scrbl

Add a note about `is-a?` and occurrence typing to the "Caveats and Limitations" section of the guide.
Closes #792

doc: add example for is-a? occurrence typing limitation

---

typed-racket-doc/typed-racket/scribblings/ts-reference.scrbl

Add a bibliography to the TR reference.
At first, I just wanted to link to POPL 2008, ICFP 2010, and SNAPL 2017. But after I got started, it made sense to just link everything I could think of.

doc: cite Typed Racket papers

---

typed-racket-more/info.rkt
typed-racket-more/typed/web-server/http.rkt

This brings TR in line with the new constant defined a few weeks ago.

Add JSON MIME type

---

rfcs/text/0002-typechecking-struct-proper-values.md
typed-racket-doc/typed-racket/scribblings/reference/types.scrbl
typed-racket-lib/typed-racket/HISTORY.txt

Struct-Property doc

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-lib/typed-racket/env/init-envs.rkt
typed-racket-lib/typed-racket/infer/infer-unit.rkt
typed-racket-lib/typed-racket/private/parse-type.rkt
typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/types/abbrev.rkt
typed-racket-lib/typed-racket/types/printer.rkt
typed-racket-lib/typed-racket/types/substitute.rkt
typed-racket-lib/typed-racket/types/subtype.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

This mostly follows the same pattern as ListDots and ValuesDots - I haven't attempted to refactor everything into an abstract "dotted type", since the similar parts are only a few lines.
No (new) test failures for me locally, and I haven't managed to break it playing around, but I'd appreciate a review by an experienced pair of eyes.
I think this closes issue #279 and part of #287.

Support dotted sequence types

---

typed-racket-doc/typed-racket/scribblings/reference/types.scrbl
typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-lib/typed-racket/base-env/base-types-extra.rkt
typed-racket-lib/typed-racket/base-env/base-types.rkt
typed-racket-lib/typed-racket/env/init-envs.rkt
typed-racket-lib/typed-racket/infer/infer-unit.rkt
typed-racket-lib/typed-racket/private/parse-type.rkt
typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-lib/typed-racket/types/abbrev.rkt
typed-racket-lib/typed-racket/types/printer.rkt
typed-racket-lib/typed-racket/types/subtype.rkt
typed-racket-lib/typed-racket/types/utils.rkt
typed-racket-test/fail/imp-outside-sp.rkt
typed-racket-test/fail/self-outside-sp.rkt
typed-racket-test/fail/untyped-struct-properties-with-self.rkt
typed-racket-test/succeed/user-defined-sp.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

support user-defined type annotations for struct properties

---

typed-racket-lib/typed-racket/base-env/base-env.rkt

[Documentation on port-number? and listen-port-number?](https://docs.racket-lang.org/reference/tcp.html#%28def._%28%28lib._racket%2Ftcp..rkt%29._port-number~3f%29%29)
I am pretty new to TR, let me know if I missed anything! :)

Add types for port-number? and listen-port-number?

---

typed-racket-more/typed/web-server/http.rkt

Should I also bump the version of typed-racket-more?

Provide TR analogue of the web-server's response/empty convenience function

---

typed-racket-compatibility/typed/scheme/base.rkt
typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl
typed-racket-lib/typed-racket/base-env/prims.rkt
typed-racket-lib/typed-racket/private/with-types.rkt
typed-racket-lib/typed/racket/base.rkt
typed-racket-test/succeed/with-handlers-star.rkt

add type for prim with-handlers*

---

typed-racket-lib/typed-racket/types/overlap.rkt
typed-racket-test/unit-tests/remove-intersect-tests.rkt

Fix overlap between (List A ...) and (List).

---

typed-racket-lib/typed-racket/base-env/for-clauses.rkt
typed-racket-lib/typed-racket/base-env/prims.rkt

Depends on racket/racket#3422. Closes #972.

Avoid for-clause optimization.

---

typed-racket-doc/typed-racket/scribblings/reference/types.scrbl
typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-lib/typed-racket/base-env/base-types-extra.rkt
typed-racket-lib/typed-racket/env/init-envs.rkt
typed-racket-lib/typed-racket/private/parse-type.rkt
typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/typecheck/tc-funapp.rkt
typed-racket-lib/typed-racket/types/base-abbrev.rkt
typed-racket-lib/typed-racket/types/printer.rkt
typed-racket-lib/typed-racket/types/subtype.rkt
typed-racket-test/fail/contract-for-self.rkt
typed-racket-test/fail/extract-sp-apply-not-self.rkt
typed-racket-test/succeed/extract-sp-apply-self.rkt
typed-racket-test/succeed/structs-has-subtype.rkt
typed-racket-test/succeed/test-spt-typed-untyped.rkt
typed-racket-test/succeed/user-defined-sp.rkt
typed-racket-test/unit-tests/interactive-tests.rkt
typed-racket-test/unit-tests/parse-type-tests.rkt
typed-racket-test/unit-tests/subtype-tests.rkt

The other day, the original name suddenly looked off to me....
I should have chosen Some in the first place ....

rename Exist to Some

---

typed-racket-lib/typed-racket/typecheck/tc-expression.rkt
typed-racket-test/succeed/gh-issue-957.rkt

fixes #957

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/succeed/callcc.rkt

fix missing prompt-tag for call/cc

---

typed-racket-lib/typed-racket/typecheck/tc-funapp.rkt
typed-racket-test/succeed/gh-issue-987.rkt

remove an expression for debugging

---

typed-racket-lib/typed-racket/base-env/base-special-env.rkt
typed-racket-lib/typed-racket/infer/infer-unit.rkt
typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-special.rkt
typed-racket-test/succeed/gh-issue-974.rkt

full support for sequence types in `for` forms

---

typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-test/fail/gh-issue-601.rkt

put bindings of structs' extra constructors in deftbl in the main type-check

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-lib/typed/racket/date.rkt

Now we can make robust custom input ports in typed racket directly.

Custom port

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/succeed/memory.rkt

Reported by James Cook in the mailing list

base-env: fix the type of current-memory-use

---

typed-racket-lib/typed-racket/base-env/base-env.rkt

base-env: add environment-variables-copy

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-lib/typed-racket/types/base-abbrev.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

fix the types for procedure-rename and procedure->method

---

typed-racket-lib/typed-racket/typecheck/check-subforms-unit.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

improve handling with-handlers

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/succeed/gh-issue-1045.rkt

fix inconsistency between the types and docs for read-bytes.*

---

typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

This bug report was brought to you by
http://drdr.racket-lang.org/56628/racket/share/pkgs/typed-racket-test/tr-random-testing.rkt

fix a bug in the specification for types of quotient &/ remainder

---

typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt

Should fix the lambda-sh package. Fixes changes in #1040.
cc @capfredf @wargray

Repair types for quotient/remainder.

---

typed-racket-lib/typed-racket/base-env/prims-contract.rkt
typed-racket-lib/typed-racket/typecheck/def-binding.rkt
typed-racket-lib/typed-racket/typecheck/internal-forms.rkt
typed-racket-lib/typed-racket/typecheck/provide-handling.rkt
typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-lib/typed-racket/utils/utils.rkt
typed-racket-test/fail/gh-issue-1050.rkt
typed-racket-test/succeed/struct-constructors.rkt

fix a bug in generating struct-related bindings

---

.github/workflows/ci.yml
typed-racket-lib/typed-racket/env/lexical-env.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/dep-function.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/exist.rkt
typed-racket-lib/typed-racket/typecheck/tc-expr-unit.rkt
typed-racket-lib/typed-racket/types/subtype.rkt

also enables contracts for integrated tests on the github ci

fix bugs exposed by contracts

---

typed-racket-lib/typed-racket/private/parse-type.rkt
typed-racket-test/fail/gh-issue-1014.rkt

parse `All`: check if the underlying symbols of type vars are duplicated

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/succeed/gh-issue-1079.rkt

add the type of filter-read-input-port

---

typed-racket-test/fail/cast-mod1.rkt

see https://github.com/racket/racket/commit/808ea5f3034549695ec5756eac0ac44b644c29f6

use <line>:<col> instead of <line>.<col> in exn-pred

---

typed-racket-lib/typed-racket/rep/prop-rep.rkt
typed-racket-lib/typed-racket/typecheck/tc-envops.rkt
typed-racket-test/succeed/internal-contract-check1.rkt
typed-racket-test/succeed/internal-contract-check2.rkt

fix internal contract errors

---

typed-racket-lib/typed-racket/base-env/base-env.rkt

fix the type for regexp-match*

---

typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-eq.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

for (equal? a b), when the type of a has an overlap with that of b,
i.e the meet of those two types are not Bottom, put the overlap in the true
proposition.

improve the true proposition from the type of equal/eqv/eq

---

typed-racket-test/gui/succeed/gui-contract.rkt

see https://github.com/racket/racket/issues/3873 for matthew's detailed explanation

make the test `gui-contract.rkt` able to exit when running on mac

---

typed-racket-lib/typed-racket/base-env/base-env.rkt

Add `index-where` from `racket/list`.

---

typed-racket-doc/info.rkt
typed-racket-doc/typed-racket/scribblings/guide/caveats.scrbl
typed-racket-doc/typed-racket/scribblings/guide/types.scrbl
typed-racket-doc/typed-racket/scribblings/reference/legacy.scrbl
typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl
typed-racket-doc/typed-racket/scribblings/reference/types.scrbl
typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-lib/typed-racket/base-env/prims-struct.rkt
typed-racket-lib/typed-racket/rep/rep-utils.rkt
typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/typecheck/internal-forms.rkt
typed-racket-lib/typed-racket/typecheck/tc-app-helper.rkt
typed-racket-lib/typed-racket/typecheck/tc-funapp.rkt
typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt
typed-racket-lib/typed-racket/types/overlap.rkt
typed-racket-test/fail/bad-prop-procedure1.rkt
typed-racket-test/fail/bad-prop-procedure2.rkt
typed-racket-test/fail/bad-prop-procedure3.rkt
typed-racket-test/fail/bad-prop-procedure4.rkt
typed-racket-test/fail/bad-prop-procedure5.rkt
typed-racket-test/fail/gh-issue-293.rkt
typed-racket-test/succeed/prop-procedure.rkt
typed-racket-test/succeed/struct-custom-type.rkt
typed-racket-test/unit-tests/interactive-tests.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt
typed-racket/info.rkt

support prop:procedure

---

README.md

@samth suggested that I add these descriptions to the readme.

Directory Guide

---

typed-racket-lib/typed-racket/typecheck/toplevel-trampoline.rkt
typed-racket-lib/typed-racket/types/tc-result.rkt
typed-racket-test/unit-tests/interactive-tests.rkt

1. only subtypes of Number are generalized at top level
2. move the code to tc-result

fix and refactor print type result at top level

---

README.md

[![Racket](https://img.shields.io/badge/-Made%20with%20Racket-darkred?logo=racket)](https://racket-lang.org)
[![Discourse users](https://img.shields.io/discourse/users?label=Discuss%20on%20Racket%20Discourse&logo=racket&server=https%3A%2F%2Fracket.discourse.group)](https://racket.discourse.group/)
[![Racket Discord](https://img.shields.io/discord/571040468092321801?label=Chat%20on%20Racket%20Discord&logo=racket)](https://discord.gg/6Zq8sH5)

community link badges

---

typed-racket-lib/typed-racket/base-env/annotate-classes.rkt
typed-racket-lib/typed-racket/private/syntax-properties.rkt
typed-racket-lib/typed-racket/private/type-annotation.rkt
typed-racket-lib/typed-racket/typecheck/tc-lambda-unit.rkt
typed-racket-lib/typed-racket/utils/utils.rkt
typed-racket-test/fail/gh-issue-862.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

Fix rest args

---

typed-racket-lib/typed-racket/types/resolve.rkt
typed-racket-test/succeed/gh-issue-1196.rkt

fix: resolve-name handles unregistered names gracefully

---

typed-racket-lib/typed-racket/typecheck/tc-lambda-unit.rkt
typed-racket-test/succeed/gh-issue-1201.rkt

repair checking optional lambdas

---

typed-racket-lib/typed-racket/private/parse-type.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

improve error recovery during parsing case-> in side-effect-mode

---

typed-racket-lib/typed-racket/typecheck/signatures.rkt
typed-racket-lib/typed-racket/typecheck/tc-expr-unit.rkt
typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt
typed-racket-test/succeed/gh-issue-782.rkt

enable proposition propagation when checking module-level exprs

---

typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

rule out NaN in true props in types of positive? and negative?

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

repair the type for vector->immutable-vector

---

.github/workflows/ci.yml

ci: do not check with-linear-integer-arith2.rkt with PLT_TR_CONTRACTS on

---

.github/workflows/resyntax-analyze.yml
.github/workflows/resyntax-submit-review.yml

Made some typos. Unfortunately, it's very hard to detect issues like that before merging pull requests. Here's hoping this doesn't require too much fiddling to get right.

Fix Resyntax workflows

---

typed-racket-lib/typed-racket/env/type-alias-helper.rkt
typed-racket-lib/typed-racket/env/type-constr-env.rkt
typed-racket-lib/typed-racket/private/parse-type.rkt
typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/private/user-defined-type-constr.rkt
typed-racket-lib/typed-racket/rep/free-variance.rkt
typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-lambda.rkt
typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-list.rkt
typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt
typed-racket-test/succeed/builtin-type-constr-cross-module.rkt
typed-racket-test/succeed/poly-lists.rkt
typed-racket-test/succeed/recursive-type-constr-contract.rkt
typed-racket-test/succeed/type-constr-contract.rkt

fix http://drdr.racket-lang.org/61098/cs/racket/share/pkgs/plot-test/plot/tests/PRs/42.rkt

contract: repair contract generation for type application

---

typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-keywords.rkt
typed-racket-test/fail/hash-union.rkt
typed-racket-test/send-places.rkt

fix an internal errror

---

typed-racket-doc/typed-racket/scribblings/reference/libraries.scrbl

Improve documentation for issue #1271.

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/succeed/function.rkt

```racket
Welcome to Racket v8.7 [cs].
> (:print-type const*)
(All (a b ...)
(case->
(-> (-> Any * (values)))
(-> a (-> Any * a))
(-> a b ... b (-> Any * (values a b ... b)))
(-> Any * (-> Any * AnyValues))))
```

Add type to `const*`.

---

.github/workflows/resyntax-analyze.yml

resyntax: fix #1302

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/succeed/gh-issue-1320.rkt

repair the type for input-port-append

---

typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt
typed-racket-test/succeed/gh-issue-1298.rkt

repair types for <, >, min and max

---

typed-racket-test/external/succeed/optional-math-untyped-id.rkt
typed-racket-test/external/succeed/shallow-math-untyped-id.rkt

Once https://github.com/racket/math/pull/68 is merged, this should be good.
Before that, the CI will fail.

test: uncomment math-untyped-id tests

---

typed-racket-lib/typed-racket/base-env/base-special-env.rkt

add types for new check procedures in `for`

---

typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-lambda.rkt
typed-racket-test/succeed/for-list-expansion.rkt

Adapts to future changes in racket/racket#4845.

Generalize for/list handling a bit.

---

typed-racket-lib/typed-racket/utils/any-wrap.rkt
typed-racket-test/succeed/any-wrap.rkt

any-wrap: do best effort to preserve identity

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-lib/typed-racket/base-env/base-special-env.rkt

This is to support https://github.com/racket/racket/pull/5020

Handle keyword variants of file operations.

---

.github/workflows/resyntax-analyze.yml
.github/workflows/resyntax-autofixer.yml

It's scheduled to run every Friday at midnight and limit pull requests to at most 20 fixes and 3 modified files.

Add Resyntax Autofixer workflow

---

typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl
typed-racket-lib/typed-racket/base-env/for-clauses.rkt
typed-racket-lib/typed-racket/base-env/prims.rkt
typed-racket-test/succeed/for.rkt

[for] Support `#:do` and `#:splice`
