typed-racket-more/typed/net/base64.rkt

base64-encode takes an optional argument newline-bstr which is absent from the type provided.

Add type for base64-encode optional argument

---

typed-racket-lib/typed-racket/typecheck/tc-let-unit.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

let-aliasing initially forgot to check if a variable that might act as
an alias was ever mutated. fixed by disallowing a mutated variable to
act as an alias.

fixed mutation let-aliasing bug

---

typed-racket-lib/typed-racket/env/lexical-env.rkt
typed-racket-lib/typed-racket/typecheck/tc-expr-unit.rkt
typed-racket-lib/typed-racket/types/path-type.rkt

fixes odd corner case internal errors where an alias's path doesn't check as a subtype of the type of the variable.
1) For example error, download tar:
https://www.dropbox.com/s/m0lj8n82z2xwogr/funky-typed.tar?dl=0
2) untar
3) racket funky-typed/synth/synth.rkt
With this commit, the internal error this currently triggers disappears and instead typechecking errors with a type mismatch on Array (this file does some non-standard usage of some of the private internals of the math/array library that doesn't work out). So both break, but this commit ensures it is a user level error for this case (i.e. a readable typechecker error) instead of a misleading internal path-mismatch error.

path-type allow non-subtype struct acc

---

typed-racket-lib/typed-racket/rep/object-rep.rkt
typed-racket-lib/typed-racket/typecheck/check-class-unit.rkt
typed-racket-lib/typed-racket/typecheck/tc-envops.rkt
typed-racket-lib/typed-racket/types/path-type.rkt
typed-racket-lib/typed-racket/utils/mutated-vars.rkt
typed-racket-test/unit-tests/class-tests.rkt

Adds occurrence typing for private fields. This has been implemented on an experimental branch for a while. The new thing is that it now comes with mutation checking in the class body to disable occurrence typing when necessary.
Code reviewers: my main concern is that the use of `FieldPE` path elements on the object of the accessor function is too hacky (see code in `tc-envops.rkt`). I can't think of any other way to implement it though.

Added occurrence typing for private fields.

---

typed-racket-more/typed/net/uri-codec.rkt

While trying to use uri-unreserved-encode discovered it and several other functions in net/uri-codec were not provided by typed/net/uri-codec
Have added the missing type signatures for these unctions. Have also made the signature of current-alist-separator-mode more precise, as previously it would typecheck when you passed it an invalid value.

Add missing type signatures for net/uri-codec

---

typed-racket-lib/typed-racket/env/type-alias-helper.rkt
typed-racket-lib/typed-racket/env/type-name-env.rkt
typed-racket-lib/typed-racket/types/base-abbrev.rkt
typed-racket-test/succeed/gh-issue-26.rkt

For unions of multiple type aliases the new placeholder would cause union collapsing incorrectly. Put an uninterned symbol in the placeholder types to avoid this.
@samth @lexi-lambda any feedback?

Adjust the fix in 619d6945c3263d21e

---

typed-racket-lib/typed-racket/base-env/colon.rkt
typed-racket-lib/typed-racket/typecheck/check-class-unit.rkt
typed-racket-lib/typed-racket/typecheck/internal-forms.rkt
typed-racket-lib/typed-racket/typecheck/tc-let-unit.rkt
typed-racket-more/typed/untyped-utils.rkt

These changes make TR work with both the current macro expander and one that has a different underlying model of binding (but is only slightly different on the outside).

adjustments to accommodate a different macro system

---

typed-racket-more/typed/pict.rkt

Self-explanatory; these types were just missing a parameter for each case.

Fix the types for pin-over and pin-under in typed/pict

---

typed-racket-lib/typed-racket/base-env/base-env.rkt

(order-of-magnitude n) is only negative if n < 1. Hence it is non-negative for all positive integers.

Make order-of-magnitude more specific

---

typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt
typed-racket-lib/typed-racket/typecheck/tc-subst.rkt
typed-racket-test/optimizer/tests/list.rkt
typed-racket-test/unit-tests/metafunction-tests.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

This also contains commits for changing tc-subst so that the simplification works.
@andmkent Can you review the first, and @stamourv can you review the second?

Simplify type for abs

---

typed-racket-lib/typed-racket/types/base-abbrev.rkt
typed-racket-test/unit-tests/class-tests.rkt

still need to double check and test real quick... but this should fix the bug let-aliasing helped expose by discovering mutated private fields were getting objects created for them.

no objects for mutated private class fields

---

typed-racket-lib/typed-racket/env/row-constraint-env.rkt
typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/parametric.rkt
typed-racket-lib/typed-racket/static-contracts/instantiate.rkt
typed-racket-lib/typed-racket/static-contracts/parametric-check.rkt
typed-racket-lib/typed-racket/utils/sealing-contract.rkt
typed-racket-test/fail/sealing-contract-1.rkt
typed-racket-test/fail/sealing-contract-2.rkt
typed-racket-test/fail/sealing-contract-3.rkt
typed-racket-test/fail/sealing-contract-4.rkt
typed-racket-test/succeed/sealing-contract-1.rkt
typed-racket-test/succeed/sealing-contract-2.rkt
typed-racket-test/succeed/sealing-contract-3.rkt

This enables contract generation for row polymorphic types for values from untyped code.
Depends on the class sealing/unsealing operations that are in a PR for core Racket: https://github.com/plt/racket/pull/912
The implementation for static contracts is pretty close to `parametric->/sc`. The `utils/sealing-contract.rkt` file does the heavy lifting and implements a contract combinator that is related to `parametric->/c`.

Add sealing contracts for row polymorphic types

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

This change allows partition to accept a predicate that only takes the types that are in the list (or some super-set of that), and allows these predicates to return Any instead of Boolean, and it only cares about the positive side of the filter.

change type of partition

---

typed-racket-lib/typed-racket/base-env/colon.rkt

Fixes check-syntax arrows for the id and optional second :

Cancel marks for 'disappeared-use ids in colon macros

---

typed-racket-lib/typed-racket/tc-setup.rkt
typed-racket-lib/typed-racket/utils/utils.rkt

It seems that both of these parameters had the intent of printing expanded syntax before typechecking. This pull request merges the behavior into the `print-syntax?` parameter, allowing expanded syntax to be printed based on a single flag in tc-setup.rkt

Merge `print-syntax?` and `show-input?` parameters into just the `print-syntax?` parameter

---

typed-racket-lib/typed-racket/private/type-annotation.rkt
typed-racket-lib/typed-racket/typecheck/tc-let-unit.rkt
typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt

This is the correct change for how attempting to bind AnyValues results
caused internal type-checking errors. The root cause was get-type/infer
violating its own contract by using the default return value from
tc-error/expr
This (partially) reverts 5e0e8ed713f3d607153a9e0fc1443d7b7bccf79b.
Fix is related to [this failing DrDr run](http://drdr.racket-lang.org/30735/racket/share/pkgs/typed-racket-test/with-tr-contracts.rkt).

Fix attempt at handling internal errors when binding AnyValues results

---

typed-racket-doc/typed-racket/scribblings/reference/exploring-types.scrbl
typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-lib/typed-racket/base-env/prims-contract.rkt
typed-racket-lib/typed-racket/base-env/prims-struct.rkt
typed-racket-lib/typed-racket/base-env/top-interaction.rkt
typed-racket-lib/typed-racket/core.rkt
typed-racket-lib/typed-racket/tc-setup.rkt
typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt
typed-racket-lib/typed-racket/typecheck/toplevel-trampoline.rkt
typed-racket-lib/typed-racket/utils/lift.rkt
typed-racket-test/unit-tests/interactive-tests.rkt

This pull request reimplements top-level typechecking. This new approach fixes the PR13747 regression due to the new expander and lets us eliminate hacks used to support the top-level. It is an alternative to PR #172.
One slight backwards incompatibility is that I changed `:print-type` and related functions to only work on expressions and not definitions or other top-level only constructs such as `require/typed`. I doubt people ever use `:print-type` on anything but expressions, so this seems ok.
I'll squash most of these commits before pushing.

Reimplement toplevel typechecking with trampoline macros

---

typed-racket-lib/typed-racket/optimizer/unboxed-let.rkt

The let unboxing optimization would drop the location of a syntax object it reassembled, because `this-syntax` was bound to something unexpected.

fixed unbox-let optimization srcloc propigation

---

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-test/succeed/integer-contracts.rkt

In the contract for `Nonpositive-Integer`, `nonpositive?` was misspelled as `nonpostive?`, creating an unbound identifier error when a contract needed to be generated.

Fix typo in generated contract for Nonpositive-Integer

---

typed-racket-lib/typed-racket/types/union.rkt

This commit seems to help cut down typechecking time. I tried compiling the math library and also `new-metrics.rkt` with/without the commit and saw about a 10% speedup.
Can someone else try to confirm the speedup?

Memoize the Un constructor for unions

---

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt
typed-racket-lib/typed-racket/utils/redirect-contract.rkt

This fixes a performance regression in TR from v6.1.1 to v6.2 that @rfindler discovered.
The regression is due to a combination of two problems. One is some overaggressive definition lifting by the contract generation pass. The other is due to the expansion of contract definition submodule redirection macros.
You can observe the problem by running `typed-racket-test/performance/function-contract.rkt`. In v6.1.1 it should take about 90ms. HEAD is about 270ms. This PR should bring it back down to around 90ms.
There's a problem though, which is that it fails two tests because of something weird with the top-level.
Here's a minimal interaction showing the problem:
````
-> (module a typed/racket
(: x (Boxof Integer)) (define x (box 3))
(provide x))
-> (require 'a)
-> (set-box! x "foo")
-> x
; …
```

Make TR's contract generation interact better with contract system optimizations

---

typed-racket-lib/typed-racket/env/global-env.rkt
typed-racket-lib/typed-racket/env/signature-env.rkt
typed-racket-lib/typed-racket/env/type-alias-env.rkt
typed-racket-lib/typed-racket/env/type-name-env.rkt
typed-racket-lib/typed-racket/typecheck/provide-handling.rkt
typed-racket-lib/typed-racket/types/struct-table.rkt

Traverse many dictionaries in sorted order when generating residual code.
Closes racket/racket#1138.

Progress towards deterministic TR compilation.

---

typed-racket-doc/typed-racket/scribblings/reference/libraries.scrbl
typed-racket-more/typed/net/url.rkt

This includes documentation for the types exported by most of the wrapper libraries, and two minor changes to the types exported by typed/net/url.

Add type docs & net/url type fixes

---

typed-racket-doc/typed-racket/scribblings/reference/experimental.scrbl

Clarifies that `define-new-subtype` defines a type-level distinction that is not there at runtime, and that this means `make-predicate` can't distinguish the new type from the base type.

Clarify define-new-subtype docs

---

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/structural.rkt
typed-racket-lib/typed-racket/utils/promise-not-name-contract.rkt
typed-racket-test/succeed/promise-provide-generate-contract.rkt

See also commit 5cd5f77 “Don't allow promises created with `delay/name` as `(Promise T)`.”.
The contracts in `typed-racket-lib/typed-racket/static-contracts/combinators/structural.rkt` should be just a single identifier, not a lambda expression, because `typed-racket-lib/typed-racket/private/type-contract.rkt` relies on that, and passes the contract name to `free-identifier=?`, which won't work on a lambda.

Fixes GH issue #268 “Can't provide promise for polymorphic struct”.

---

typed-racket-lib/typed-racket/base-env/base-env.rkt

fixes https://github.com/racket/typed-racket/issues/277
Can’t make it polymorphic, settle for `Any -> (Listof Any)`

add type for flatten

---

typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl
typed-racket-lib/info.rkt
typed-racket-lib/typed-racket/base-env/prims-contract.rkt
typed-racket-lib/typed-racket/base-env/prims-struct.rkt
typed-racket-lib/typed-racket/typecheck/internal-forms.rkt
typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt
typed-racket-test/succeed/require-typed-struct-custom-type.rkt
typed-racket-test/succeed/struct-custom-type.rkt

This change affects all the struct definition forms as well as `#:struct` clauses in `require/typed`. It's something I've been wanting to change for a while, but I've only now gotten around to doing it. The change is simple and can probably best be explained in code.
```racket
(struct [point : Point] ([x : Real] [y : Real]))
```
This creates a struct called `point`, but the *type* generated for it is `Point`. The change to `require/typed` is the same.
```racket
(require/typed
net/url-structs
[#:struct [path/param : Path/Param]
([path : (U String 'up 'same)]
[param : (Listof String)])])
```
Capitalization is, unsurprisingly, the main motivator behind this change, which lets both naming conventions be satisfied without needing any type aliases.

Allow the types created for structs to be specified manually instead of always generating them from the struct name

---

typed-racket-doc/typed-racket/scribblings/reference/types.scrbl

Make the example typeset in a Racket build that does not support
extflvectors.

adjust doc `extfvector` example

---

typed-racket-test/succeed/define-typed-untyped-identifier-syntax-properties.rkt

@stamourv I saw that I had left some stale debugging output in the PR #323 you merged yesterday. I suppose you'll want to remove it, so this patch just removes the couple of `(displayln …)`. Sorry about that.

Remove debugging output from test case in PR 323

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

To return `(U False (Listof (Syntaxof Any)))` if it can't prove that the input is a syntax-list.
Fixes https://github.com/racket/typed-racket/issues/347
This makes the type of `syntax->list` consistent with the type `stx->list` already has.

Fix type of syntax->list

---

typed-racket-lib/typed-racket/base-env/base-types-extra.rkt
typed-racket-lib/typed-racket/env/init-envs.rkt
typed-racket-lib/typed-racket/infer/infer-unit.rkt
typed-racket-lib/typed-racket/infer/restrict.rkt
typed-racket-lib/typed-racket/private/parse-type.rkt
typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/static-contracts/constraints.rkt
typed-racket-lib/typed-racket/typecheck/tc-expr-unit.rkt
typed-racket-lib/typed-racket/typecheck/tc-literal.rkt
typed-racket-lib/typed-racket/types/printer.rkt
typed-racket-lib/typed-racket/types/remove-intersect.rkt
typed-racket-lib/typed-racket/types/subtype.rkt
typed-racket-test/succeed/intersection1.rkt
typed-racket-test/unit-tests/contract-tests.rkt
typed-racket-test/unit-tests/parse-type-tests.rkt
typed-racket-test/unit-tests/remove-intersect-tests.rkt
typed-racket-test/unit-tests/subtype-tests.rkt

Adds intersection types as a better to handle the the case when restrict cannot intersect two types, allowing for non-lossy refinements of type info.

initial intersection types addition

---

typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-lib/typed-racket/types/remove-intersect.rkt
typed-racket-test/fail/no-setters-for-built-in-structs.rkt
typed-racket-test/fail/poly-struct-mutable-parent.rkt
typed-racket-test/succeed/gh-issue-205.rkt

This PR fixes issue #205 and some related bugs I found, but unfortunately there is one test that doesn't pass right now.
I think that the test actually exhibits broken behavior, so I wanted a second opinion on what to do about it.
The problematic test is this one: https://github.com/racket/typed-racket/blob/master/typed-racket-test/succeed/poly-struct-parent.rkt
On my PR branch, line 25 fails to typecheck because the predicate on that line has a filter that overlaps with the `Box2` type. Unfortunately, the original behavior (that the types don't overlap) is also wrong because it makes that whole conditional branch into dead code (try adding `(+ 1 "foo")` in that cond branch). Anyone have suggestions on how to fix this test?

Fix github issue #205

---

typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl
typed-racket-lib/typed-racket/base-env/prims-contract.rkt
typed-racket-lib/typed-racket/private/cast-table.rkt
typed-racket-lib/typed-racket/private/syntax-properties.rkt
typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/private/with-types.rkt
typed-racket-lib/typed-racket/typecheck/tc-expression.rkt
typed-racket-test/succeed/cast-mod.rkt
typed-racket-test/succeed/cast-top-level.rkt

Fixes https://github.com/racket/typed-racket/issues/108
Fixes PR 13626
Fixes PR 14955
This makes `cast` generate two contracts, one from typed to untyped using the original type of the expression, and one from untyped to typed, using the type it's casting to. 
So in examples like this:
```racket
(: v Boolean)
(define v #f)
(: f (Boolean -> Boolean))
(define (f x)
(set! v x)
x)
v ; #f
((cast f (String -> String)) "hello") ; error!
v ; if that hadn't been an error, this would be "hello" with type Boolean
```
The cast applies a contract for the new type `String -> String` going from untyped to typed, but first it applies a contract for the old type, `Boolean -> Boolean`, going from typed to untyped. This also means that doing `((cast f (Boolean -> Boolean)) #t)` succeeds …

Close cast soundness loophole

---

typed-racket-lib/typed-racket/base-env/base-special-env.rkt

Currently, `in-port` returns `(Sequenceof Any)` unconditionally, which is correct if the given read function is `read` (default value). However, `(in-port read-line)`, `(in-port read-char)`, etc. should have more specific types.

Give correct type to `in-port` when used with custom reader

---

typed-racket-lib/typed-racket/base-env/prims-contract.rkt

Programs that use `cast` on values with types that can't be converted to contracts currently raise errors about `syntax-source` not receiving a syntax object. This pull request fixes those so that they raise the normal contract generation errors, with the source location of the casted expression.
For example this program
```racket
(define v (ann (vector 1) VectorTop))
(cast v Any)
```
Currently raises the error
```
. . ../../Applications/Racket/2016-06-16/Racket v6.5.0.5/share/pkgs/source-syntax/source-syntax.rkt:78:2: syntax-source: contract violation
expected: syntax?
given: (VectorTop 940 (combined-frees (make-immutable-hasheq) empty) (combined-frees (make-immutable-hasheq) empty) false 'vector)
```
With this pull request, this program fails with the message
```
. …
```

fix the error message in issue #375

---

typed-racket-lib/typed-racket/base-env/prims-contract.rkt
typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-test/succeed/cast-mod.rkt

For `VectorTop`, `HashTableTop`, etc. going from typed to untyped.
This fixes examples like
```racket
(define v (ann (vector 1) VectorTop))
(cast v Any)
```
To generate `(and/c vector? any-wrap/c)` contracts instead of raising a compile-time contract-generation error. This reduces some of the backwards-incompatibility from the `cast` soundness fix.
This fixes some of the problems in https://github.com/racket/typed-racket/issues/375, although parts of ~~both measures-with-dimensions and~~ `wrap` are still failing for other reasons.

add (and/c vector? any-wrap/c) -like contracts

---

typed-racket-lib/typed-racket/static-contracts/structures.rkt

This pull requests implements the `sc->constraints` generic method for the `recursive-sc` struct.
This changes the error in the `wrap` package mentioned in issue #375 here (https://github.com/racket/typed-racket/issues/375#issuecomment-228580196),
From this:
```
. . ../../../../../../../../../../Applications/Racket/2016-06-16/Racket v6.5.0.5/collects/racket/private/generic.rkt:488:0: 
sc->constraints: not implemented for
(recursive-sc
(list #<syntax scan1681546> #<syntax scan1681547> #<syntax scan1681548>)
(list (or/sc2 (list (simple-contract #<syntax:/Applications/Racket/2016-06-16/Racket v6.5.0.5/share/pkgs/typed-racket-lib/typed-racket/private/type-contract.rkt...
```
To this:
```
. Type Checker: Type (U Null (Pairof JsObject (∩ JsList (Listof HashTableTop)))) could not be converted to …
```

implement sc->constraints for recursive-sc

---

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-test/fail/sandboxed-unsafe-ops.rkt
typed-racket-test/succeed/cast-mod.rkt

This fixes programs like:
```
(define-type T
(Rec T (U String (Listof T))))
(: f : (Listof T) -> Any)
(define (f x)
(if (andmap list? x)
(cast x Any)
#f))
```
Where there is a `cast` from a value with an intersection type that involves recursive types that can be guarded with flat contracts.
This fixes another part of issue #375 discussed in https://github.com/racket/typed-racket/pull/381#issuecomment-230509639, which pull request #381 fell short of solving.

call compute-constraints instead of sc->constraints in get-max-contract-kind

---

typed-racket-lib/typed-racket/base-env/prims-contract.rkt
typed-racket-test/fail/cast-tyvar.rkt

On  `cast`s from types with free-variables, this raises a proper contract-generation type error instead of throwing an internal error. For example this program from issue #380 
```racket
(: f : (All (X) (-> X X)))
(define (f x)
(cast x Any)
x)
```
Used to raise the internal error
```
. . ../../Applications/Racket/2016-06-16/Racket v6.5.0.5/share/pkgs/typed-racket-lib/typed-racket/private/type-contract.rkt:337:4: 
type->static-contract: Recursive value lookup failed. #hash() X
```
It now raises the error
```
. Type Checker: Type X could not be converted to a contract because it contains free variables.
in: x
```
With the `x` in `(cast x Any)` highlighted.

Raise a proper contract-generation error for #380

---

typed-racket-lib/typed-racket/typecheck/tc-if.rkt
typed-racket-lib/typed-racket/types/abbrev.rkt
typed-racket-test/succeed/cast-mod.rkt

Fixes #378 
This fills the corresponding entries in the cast table with a dead code type so that when the contract-generation pass calls the `contract-def` thunk, it finds that in the table.

don't throw internal errors for unreachable cast exprs

---

typed-racket-lib/typed-racket/typed-racket.rkt
typed-racket-lib/typed-racket/utils/any-wrap.rkt
typed-racket-lib/typed-racket/utils/inspector.rkt
typed-racket-test/succeed/exn-any-mutation.rkt
typed-racket-test/succeed/pr241-variation-4.rkt

Fixes #379 
This modifies `any-wrap/c` to fail on opaque things it doesn't have an inspector for, but it defines a new inspector so that normal uses of `struct` (without a special `#:inspector` argument) create structures that `any-wrap/c` can inspect.
For example on this program:
```racket
(struct (X) s ([i : X]) #:mutable)
(: s1 : (s Integer))
(define s1 (s 42))
(define s2 (ann s1 Any))
(define s3 (cast s2 (s (U Integer String))))
(set-s-i! s3 "unsound!")
;#<s>: contract violation
;  Attempted to use a higher-order value passed as `Any` in untyped code: #<s>
;  in: Any
;  contract from: typed-world
;  blaming: cast
;   (assuming the contract is correct)
;  at: /Users/Alex/Documents/DrRacket/any-wrap-opaque-example.rkt:6.11
(s-i s1) ; if that hadn't errored, this would …
```

fix any-wrap/c unsoundness on opaque structures

---

typed-racket-lib/typed-racket/utils/any-wrap.rkt

Fixes the math library failure here:
http://drdr.racket-lang.org/35897/racket/share/pkgs/math-lib/math/private/bigfloat/bigfloat-hurwitz-zeta.rkt
Relies on racket/racket#1368.
Relevant to #385.

Allow cpointer predicates as struct predicates.

---

typed-racket-test/succeed/pr241-variation-5.rkt

Checks that `environment-variables?` values can pass through the `Any` contract.

add any-wrap test for Environment-Variables

---

typed-racket-lib/typed-racket/base-env/prims-contract.rkt
typed-racket-lib/typed-racket/utils/any-wrap.rkt

see https://github.com/racket/typed-racket/pull/385#issuecomment-231354377
This allows passing opaque structs as `Any` into `#:opaque` predicates without wrapping them properly, even though it's unsound. It displays a warning message instead of raising an error.

add a version of any-wrap/c that displays a warning on opaque structs

---

typed-racket-lib/typed-racket/types/overlap.rkt
typed-racket-test/succeed/pr403.rkt

fixes a bug (#403) ```overlap?``` triggered (an infinite loop which continually unfolded recursive types) by keeping around previously seen types and checking against them.

have overlap use a current-seen list

---

typed-racket-lib/typed-racket/static-contracts/combinators/simple.rkt
typed-racket-test/succeed/pr15330.rkt
typed-racket-test/unit-tests/static-contract-equality-tests.rkt

This is a fix intended to go into the TR release for PR 15330.
There are several ways to fix this. The one I chose was changing the equality to traverse syntax objects by structure, comparing leaves by free-id=? for identifiers and equal? otherwise.
Another option would be to add an (optional) value to these static contracts that is used for equality checking. Then we could stuff the struct predicate identifier in there for struct contracts.
Yet another is to compile struct contracts specially, avoiding using `flat/sc`.
Any opinions on which approach is best?

Fix contracts for structs with the same name (PR 15330)

---

typed-racket-lib/typed-racket/base-env/base-special-env.rkt
typed-racket-lib/typed-racket/utils/lift.rkt

These two commits are intended to support a revised expansion of function definitions that have mandatory keyword arguments. The first commit is a more general repair to support `syntax-local-lift-values-expression` in full. The second commit is specific to the keyword expansion.
A branch of Racket with the change to keyword expansion (plus related optimizer changes): mflatt/racket@ad230d2ca09ee45002eaa1bea24a1e8ce933e3a9 (the `mandatory-keywords` branch).

Support for changes mandatory-keyword expansion

---

typed-racket-doc/typed-racket/scribblings/reference/libraries.scrbl
typed-racket-more/info.rkt
typed-racket-more/typed/db.rkt
typed-racket-more/typed/db/base.rkt
typed-racket-more/typed/db/sqlite3.rkt

working with the `db-lib` is hard in Typed Racket.
1. meanwhile only sqlite3 is usable since it does not require `struct` based datatypes;
2. `sql-null` is not protected by `any-wrap/c`.

Add support for db/base and db/sqlite3

---

typed-racket-more/typed/racket/private/gui-types.rkt

stay consistent with the (default-icon-backing-scale)

Improve type annotation of (get-backing-scale)

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/succeed/gh-issue-426.rkt

If `(non-empty-string? v)` returns true, that implies that `v` is a string, but if it returns false, that doesn't imply anything about the type of `v`.
Fixes https://github.com/racket/typed-racket/issues/426

fix type of non-empty-string?

---

typed-racket-more/typed/images/icons.rkt
typed-racket-more/typed/images/logos.rkt

1. fix the `#lang`s to avoid requiring useless APIs;
2. `#:backing-scale` accepts `Positive-Real`.

Improvements on typed/images/logos.rkt and typed/images/icons.rkt

---

typed-racket-lib/typed-racket/static-contracts/combinators/any.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/case-lambda.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/control.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/function.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/lengths.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/name.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/none.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/object.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/parametric.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/simple.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/struct.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/structural.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/unit.rkt
typed-racket-lib/typed-racket/static-contracts/constraints.rkt
typed-racket-lib/typed-racket/static-contracts/instantiate.rkt
typed-racket-lib/typed-racket/static-contracts/kinds.rkt
typed-racket-lib/typed-racket/static-contracts/optimize.rkt
typed-racket-lib/typed-racket/static-contracts/parametric-check.rkt
typed-racket-lib/typed-racket/static-contracts/structures.rkt

This PR changes numerous ```(provide (contract-out ...))``` instances to ```(provide/cond-contract ...)``` and removes some unneeded generic ```dict``` operations with more specific functions for performance sake.
Reducing this contract overhead in the ```static-contract``` directory and especially changing the particularly hot ```dict-set``` instances to ```free-id-table-set``` calls from ```syntax/private/id-table``` made _huge_ differences when type checking some parts of the Schml compiler (see this standalone [file](https://github.com/pnwamk/tr-performance/blob/master/schml-interp-casts-help.rkt)).

remove contract overhead from static-contract code

---

typed-racket-lib/typed-racket/base-env/prims-contract.rkt
typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/typecheck/tc-if.rkt
typed-racket-test/succeed/cast-mod.rkt

The previous fix relied on finding and manipulating all dead code. But we
missed some; in particular code of the form:
(begin (error 'x) ...dead...)
So switch to a different strategy that tolerates untraversed dead code.

Fix #378 more comprehensively.

---

typed-racket-lib/typed-racket/env/lexical-env.rkt
typed-racket-lib/typed-racket/env/type-env-structs.rkt
typed-racket-lib/typed-racket/typecheck/check-class-unit.rkt
typed-racket-lib/typed-racket/typecheck/check-unit-unit.rkt
typed-racket-lib/typed-racket/typecheck/tc-envops.rkt
typed-racket-lib/typed-racket/typecheck/tc-lambda-unit.rkt
typed-racket-lib/typed-racket/typecheck/tc-let-unit.rkt
typed-racket-lib/typed-racket/typecheck/tc-send.rkt
typed-racket-lib/typed-racket/typecheck/tc-subst.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

clean up tc-let-unit
This commit cleans up some helper functions that have been
pretty awful for a long time. The code is now more readable
and it does less work (i.e. unneeded substitutions are no longer
done).

clean up tc-let-unit

---

typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt

Currently, `(max Index Index)` has the type `Nonnegative-Fixnum` from the case
`(-> Nonnegative-Fixnum Fixnum * Fixnum Nonnegative-Fixnum)`
whereas I believe it should be `Index` -- this includes the case where (max 0 0) is 0 -- which is an Index
added `(-> Index * Index)` to second the varop list for the type of `max`
Is the testing automatic? Or do I need to write a test case --- if so where?

Add type (: max (Index * -> Index))

---

typed-racket-lib/info.rkt
typed-racket-lib/typed-racket/base-env/base-special-env.rkt
typed-racket-lib/typed-racket/optimizer/sequence.rkt

In racket/racket#1534, the expansion of `for` for a generic sequence has changed to receive
and use an extra result from the internal `make-sequence` function. These appear to be the needed changes for TR.
The public interface of `make-do-sequence` has also changed to allow a function that returns one more result. I don't think that anyone will ever want to provide that extra result, so I left the type as-is.

sync with change to `for` expansion (goes with racket/racket PR)

---

typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/types/prop-ops.rkt

This PR (1) removes some unnecessary nondeterminism from prop-ops and (2) fixes the issue where the `nested-poly` integration test would occasionally fail. Basically, the correctness of type checking currently relies on the `var-name-table` in `type-rep.rkt` being *persistent*... which seems odd and wrong, but that's definitely the issue. I removed the table entirely and that caused the error to consistently happen, and it seems like that program w/ its nested polymorphic applications is the only program I've run into that relied on that particular table being persistent.
A better fix I think would be to further examine how the table is used and remove this requirement --- my initial assumption was that the table was just for error reporting and printing (so that users saw types w/ the …

fix intermittent error in 8e7f390

---

typed-racket-lib/typed-racket/infer/intersect.rkt
typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/types/base-abbrev.rkt
typed-racket-lib/typed-racket/types/update.rkt
typed-racket-test/fail/issue-169-1.rkt
typed-racket-test/fail/issue-169-2.rkt
typed-racket-test/succeed/inf-nested-bot.rkt

Moving to eager propagating of bottom works for most cases,
but in some cases flattening types such as (Pairof Bottom Any)
to Bottom made things like type inference break for some cases
(since (Listof Nothing) == Null, and (Listof A) did not structurally
like up like it used to). Perhaps w/ a little more effort
inference and any other potential issues could work better
with propagating bottom, but for now we'll be slightly less
aggressive about it.
i.e. this fixes `pfds`, which commit 8e7f390 broke.

be less eager about bottom propagation

---

typed-racket-more/typed/file/glob.rkt

Typed interface to `file/glob`.
This PR is "ready to go", but if we leave it open I'll try to add types + tests for the other `file/*` libraries by the end of the month.
(Otherwise I'll still try to add those, just in a different PR)

add typed/file/glob

---

typed-racket-lib/typed-racket/utils/opaque-object.rkt
typed-racket-test/succeed/opaque-object-name.rkt
typed-racket-test/succeed/opaque-object-stronger.rkt
typed-racket-test/succeed/pr267-variation-0.rkt

Fixes the included microbenchmark. This does not seem to fix the wrappers from `fsmoo` and `forth`; those contracts must not be `eq?`.

default implementation for object/c #:stronger

---

typed-racket-doc/typed-racket/scribblings/reference/libraries.scrbl
typed-racket-more/typed/racket/gui/no-check.rkt
typed-racket-more/typed/racket/gui/no-check/lang/reader.rkt
typed-racket-test/succeed/standard-features-no-check-gui.rkt

Okay, the test case for this `#lang` does not work since it will instantiate the gui instance one more time.

Add #lang typed/racket/gui/no-check

---

typed-racket-more/typed/db/base.rkt
typed-racket-more/typed/db/sqlite3.rkt
typed-racket-test/succeed/pr468-in-query.rkt

Replaced #461 and fixed #460 
Currently, Typed Racket denies sequences that provide 3 or more values,
thus, `in-query` always returns a sequence of vector instead of value/values.
It's okay since applications may predicate column types with `match` after receiving data.
Also, this fix makes the `SQL-Datum` more precision,
since `Any` shadows all opaque types (such as `SQL-Null`) which lead to contract errors.

`in-query` returns a sequence of single value instead of result-arity-based multiple values

---

typed-racket-lib/typed-racket/private/type-contract.rkt

To cooperate better with the contract system.
This introduces a dependency to a module that (it looks like) we want to keep thin. I'd imagine that anything that requires that module would also depend on the contract system anyway, so the point is moot?

Use existing contract combinators.

---

typed-racket-lib/typed-racket/base-env/base-special-env.rkt

This is primarily intended for use on the `linklet` branch,
but does not cause problems in other contexts.

Add types for loop precondition checking functions.

---

typed-racket-doc/typed-racket/scribblings/reference/types.scrbl

An `(All (A) ....)` doesn't quantify over `(Values ....)` types

doc: comment on values vs. All

---

typed-racket-lib/typed-racket/base-env/base-env.rkt

fixes types of `port->*` functions to match new keyword argument added by Racket commit samth/racket@1309cf164930cca4dfed4956db8ff1048ded3d7f

fix port-> functions to match new kw args in impl

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/succeed/somesystempath.rkt

This seems to work --- is adding 2 new cases to the `cl->*` the right way to support the optional argument?

update path-add-extension type with new optional argument

---

typed-racket-lib/typed-racket/rep/rep-utils.rkt

I looked more closely, custom constructors were checked at _both_ the module and local level. Also, in my iterating on how to support custom contracts I ended up leaving two layers of checking in on custom constructors -- removing this reduced contract overhead on some small benchmarks by ~20%. I think this is a fair balance (and its more or less what we were doing before).

be more reasonable about constructor contract checking

---

.travis.yml
typed-racket-test/with-tr-contracts.rkt

Currently we run unit tests with our internal development contracts on as a part of our DrDr testing... but we do this without actually recompiling Typed Racket. This leads to the following:
1. The test usually takes 30 or more minutes (lately it's been 50+ minutes)
2. we often don't find out about incorrect development contracts until DrDr builds, instead of finding our as part of the PR review process
This PR moves this testing to our Travis CI builds, which seems to add about 6 or 7 minutes to the overall run time.

add contracted unit tests to travis

---

typed-racket-lib/typed-racket/typecheck/tc-literal.rkt
typed-racket-lib/typed-racket/types/generalize.rkt
typed-racket-test/succeed/literal-char-gh-issue-434.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

squashed version of PR #526 with some of the tests moved to our `unit-tests`.

use singleton char types if expected type

---

typed-racket-doc/typed-racket/scribblings/guide/optimization.scrbl
typed-racket-doc/typed-racket/scribblings/reference/optimization.scrbl
typed-racket-lib/typed-racket/tc-setup.rkt
typed-racket-test/fail/sandbox.rkt

The optimizer should only run when the code being compiled could
directly access racket/unsafe/ops. This prevents unsoundness in Typed
Racket from giving untrusted code access to dangerous operations.

Use code-inspectors to prevent optimization in unsafe contexts.

---

typed-racket-lib/typed-racket/infer/dmap.rkt
typed-racket-lib/typed-racket/infer/infer-unit.rkt
typed-racket-lib/typed-racket/infer/intersect.rkt
typed-racket-lib/typed-racket/infer/signatures.rkt
typed-racket-lib/typed-racket/rep/object-rep.rkt
typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/typecheck/check-below.rkt
typed-racket-lib/typed-racket/typecheck/tc-app-helper.rkt
typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-hetero.rkt
typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-main.rkt
typed-racket-lib/typed-racket/typecheck/tc-envops.rkt
typed-racket-lib/typed-racket/typecheck/tc-expr-unit.rkt
typed-racket-lib/typed-racket/typecheck/tc-funapp.rkt
typed-racket-lib/typed-racket/typecheck/tc-literal.rkt
typed-racket-lib/typed-racket/typecheck/tc-subst.rkt
typed-racket-lib/typed-racket/types/match-expanders.rkt
typed-racket-lib/typed-racket/types/prop-ops.rkt
typed-racket-lib/typed-racket/types/subtract.rkt
typed-racket-lib/typed-racket/types/subtype.rkt
typed-racket-lib/typed-racket/utils/utils.rkt
typed-racket-test/succeed/with-integer-linear-arith2.rkt

This PR adds more support for refinement reasoning, in particular type inference is now aware of argument objects which allows for more programs w/ refinements to typecheck. Additionally, working with vector types and literals that are refined or need to have properties about their length proven now works.
I need to add tests and peruse the changes more, but what is here at the moment seems to work and is representative of the scope I intend for this PR.
Next stop (i.e. PR), function types that support inter-argument dependency!

add more refinement support for inference and literals

---

typed-racket-lib/typed-racket/infer/intersect.rkt
typed-racket-lib/typed-racket/rep/core-rep.rkt
typed-racket-test/unit-tests/interactive-tests.rkt

intersections with resolvable types would occasionally generate
spurious weird types (e.g. μx.x) when a type name
is not yet fully defined -- this patches that problem by
using resolve-once instead of resolve and checking the result
for #f before proceeding to compute the intersection
See #541 and #532.

fix intersection bug

---

typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/utils/utils.rkt

This commit involves no functional changes, just tries to clean up some of the helper functions in type-rep, specifically those regarding instantiate/abstract for type variables.

clean up instantiate/abstract for type vars

---

typed-racket-lib/typed-racket/base-env/prims-contract.rkt
typed-racket-test/fail/require-typed-struct-missing-colon.rkt

Today I made a mistake writing a `require/typed`, I was missing a colon in the struct fields. Something like:
```
(require/typed "file.rkt"
(#:struct posn ([x Integer] [y Integer])))
```
The error message was confusing:
```
<pkgs>/typed-racket-lib/typed-racket/base-env/prims-contract.rkt:168.7: require-typed-struct: expected constructor-term
at: (((x Integer) (y Integer)) #:type-name posn (submod ".." server))
within: (require-typed-struct posn () ((x Integer) (y Integer)) #:type-name posn (submod ".." server))
in: (require-typed-struct posn () ((x Integer) (y Integer)) #:type-name posn (submod ".." server))
....
```
After this commit, the error message is better:
```
<pkgs>/typed-racket-lib/typed-racket/base-env/prims-contract.rkt:168.7: require-typed-struct: expected the identifier `:' …
```

require-typed: more informative error when struct field is missing :

---

typed-racket-lib/typed-racket/base-env/base-env.rkt

it had a nonsensical type before

fix type of 'string-environment-variable-name?'

---

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-test/succeed/pr390-variation-6.rkt

The contract for `(U (I-Hash k1 v1) (M-Hash k2 v2) (W-Hash k3 v3))`
is now `(hash/c (or/c k1 k2 k3) (or/c v1 v2 v3))`
ONLY WHEN the key and value types are distinct.
The contract should no longer include duplicate key or value types.

patch: check duplicates before making an or/c for hash keys

---

typed-racket-more/info.rkt
typed-racket-more/typed/rackunit/main.rkt

The "monad" struct in RackUnit's internals is never exposed to users and there's no requirement to use it with `fold-test-results`. The "seed" parameter in `fold-test-results` can be any value and is more accurately described by a parametric type. I'm not quite sure what the correct change to make it parametric is, but this change is necessary to remove the dependency on `rackunit/private/monad`. The monad implementation of `rackunit/text-ui` will hopefully go away soon.

Remove opaque monad type from typed/rackunit

---

typed-racket-lib/typed-racket/private/type-contract.rkt

Better than https://github.com/racket/typed-racket/commit/6c2a7eb512b8c8da26fc021aab26b2c765313fab

type-contract: use 'Un' to check overlapping hash key types

---

typed-racket-more/info.rkt
typed-racket-more/typed/rackunit/main.rkt
typed-racket-more/typed/rackunit/type-env-ext.rkt

This is an internal implementation detail of rackunit. The `current-check-around` parameter is set to `check-around` by default, so there's no need to explicitly set it in test-begin.

Remove typed/rackunit references to check-around

---

typed-racket-lib/typed-racket/base-env/base-env-indexing-abs.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

and the corresponding tests
closes #578 
`integer-bytes->integer` docs: http://docs.racket-lang.org/reference/generic-numbers.html#%28def._%28%28quote._~23~25kernel%29._integer-bytes-~3einteger%29%29

fix type of integer-bytes->integer

---

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/types/match-expanders.rkt
typed-racket-test/succeed/hashtabletop-flat-contract.rkt

Changing `HashTableTop` from a singleton to the union:
```
(U (Immutable-HashTable Any Any) MutableHashTable WeakHashTable)
```
is a backwards compatibility issue because the type `Any` requires a chaperone,
therefore `HashTableTop` requires a chaperone.
This commit adds a case to make sure `HashTableTop` generates a flat contract.
Closes #581

backwards-compatibility: make HashTableTop generate a flat contract

---

typed-racket-more/typed/rackunit/main.rkt
typed-racket-test/succeed/rackunit-suite.rkt

This adds a test and fixes a bug that [broke the `semver` package](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/semver.txt) in the latest build. The "seed" type used in TR's wrapper around rackunit could be any value, but #564 incorrectly restricted it to only objects and `#f`. It previously worked because rackunit wrapped all seed values in a special "monad" wrapper, which no longer exists. The seed values aren't used by test suites anyway, only functions that call `fold-test-results` or `foldts-test-suite`.

Fix typed/rackunit contract exception when using `run-tests`

---

source-syntax/info.rkt
source-syntax/scribblings/source-syntax.scrbl

Add documentation for `syntax/source-syntax` module.
(This fixes a TODO on the package server.)
The example is boring because it returns different results inside `examples` than in a top-level module.
I thought about using a `racketblock` instead, but I think a boring `examples` is better.

doc: scribblings for 'syntax/source-syntax'

---

.gitignore

Can we ignore vim swapfiles?
This has been bugging me for a while now.

gitignore: vim swapfiles

---

typed-racket-lib/typed-racket/static-contracts/combinators/lengths.rkt
typed-racket-test/unit-tests/static-contract-instantiate-tests.rkt
typed-racket-test/unit-tests/static-contract-optimizer-tests.rkt

Fix a bug in `list-length/sc`.
I think it's impossible to write a `#lang typed/racket` program that illustrates the bug (and doesn't use `require`). But still.

static-contracts: fix list-length/sc

---

typed-racket-doc/typed-racket/scribblings/guide/optimization.scrbl

Since its usage in the guide is to create a value of type `Float` on which TR can apply optimizations, `real->double-flonum` seems like the the better choice. The type of `exact->inexact` can sometimes produce single flonums or complex numbers, but `real->double-flonum` always returns a `Float`.
For converting exact complex numbers into inexact complex numbers I don't see another option; I'm not sure what to do there.

Should TR optimizer docs recommend real->double-flonum instead of exact->inexact?

---

typed-racket-lib/typed-racket/static-contracts/optimize.rkt
typed-racket-test/unit-tests/contract-tests.rkt

Closes #616 
Add a case to the static contract optimizer so that contracts
generated from the `Syntax` type disappear in trusted positions.
This restores the "old" behavior for the `Syntax` type --- the behavior
before fixing the 'or/c' unsoundness in issue 598.
<https://github.com/racket/typed-racket/issues/598>
Note: this fix is temporary, until the definition of `Syntax` can
be in terms of _immutable_ vectors & boxes.

static-contract: temporarily fix for incoming syntax

---

typed-racket-lib/typed-racket/env/init-envs.rkt
typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/typecheck/tc-lambda-unit.rkt
typed-racket-lib/typed-racket/types/abbrev.rkt
typed-racket-lib/typed-racket/types/base-abbrev.rkt
typed-racket-lib/typed-racket/types/kw-types.rkt
typed-racket-lib/typed-racket/types/printer.rkt
typed-racket-lib/typed-racket/types/utils.rkt
typed-racket-lib/typed-racket/utils/utils.rkt
typed-racket-test/unit-tests/parse-type-tests.rkt
typed-racket-test/unit-tests/type-printer-tests.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

Since we don't explicitly represent optional arguments in TR (i.e. we just use case-> for everything) we have converted this function type:
```racket
(->* (A) (B) #:rest C D)
```
into this function type:
```racket
(case-> (-> A C * D)
(-> A B C * D))
```
which is incorrect and unsound (see https://github.com/racket/typed-racket/issues/614). This combined with some other subtle (probably related) decisions in our handling of type checking `case-lambda` forms has been needing some work for a while.
This PR aims to fix these issues. Now the function type
```racket
(->* (A) (B) #:rest C D)
```
will be converted internally into
```racket
(case-> (-> A D)
(-> A B C * D))
```
I've been working to touch up all of the code affected by this so we no longer have issues with optional and rest args …

fix #:rest and optional args

---

typed-racket-lib/typed-racket/typecheck/tc-lambda-unit.rkt
typed-racket-test/fail/apply-dots.rkt
typed-racket-test/succeed/apply-dots.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

This adds to (i.e. __depends on__) the changes in https://github.com/racket/typed-racket/pull/618 by:
+ cleaning up our lambda checking code more
+ fixing some case-lambda issues we've had (in particular how we handle giving types to case lambdas that have no expected type (i.e. that we are checking entirely in type synthesis mode))
This fixes https://github.com/racket/typed-racket/issues/413 (possibly more).
In general, whenever we have a `case->` expected type we ensure that the body of the function checks successfully __at each type__ in the `case->`.
This also needs to happen when we are checking a `case-lambda`, however as we analyze each case, we may see that certain arrow types in the `case->` type are "unreachable" for a particular case-lambda clause (i.e. the arrow's domain would …

fix case lambda

---

typed-racket-lib/typed-racket/env/type-alias-helper.rkt
typed-racket-lib/typed-racket/private/parse-type.rkt
typed-racket-test/succeed/refinements-and-aliases.rkt

Our current approach to parsing types parses them several times, first for effect and then again later.
I've added a parameter that allows us to turn off "invariant checking" while parsing, so that the initial parse isn't worrying about whether the propositions in refinements are well typed, etc.
These invariants are later enforced when we again parse the types w/o setting the parameter to false.
This fixes the issue @AlexKnauth  found and reported in #641.

fix parsing of refinements and type aliases

---

typed-racket-doc/typed-racket/scribblings/reference/experimental.scrbl
typed-racket-lib/typed-racket/private/parse-type.rkt
typed-racket-lib/typed-racket/rep/object-rep.rkt
typed-racket-test/unit-tests/parse-type-tests.rkt

The previous syntax for linear expressions in propositions/objects was too restrictive -- this makes it much more relaxed, which will allow users more freedom to naturally express constraints in types.

more general linear exp stx for props

---

typed-racket-lib/typed-racket/typecheck/check-below.rkt
typed-racket-test/succeed/refinements-expected-type1.rkt

Allows `check-below` to use information from the type result's prop-set when checking if one result is below another.
Addresses issue identified in https://github.com/racket/typed-racket/issues/640 .

check-below uses props when with-refinements is true

---

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/static-contracts/instantiate.rkt
typed-racket-lib/typed-racket/static-contracts/optimize.rkt
typed-racket-test/succeed/issue-628.rkt

This is one idea for fixing #628 .
I'm not happy about re-computing `recursive-kinds` in the optimizer,
but I don't see how to tell whether a `name/sc` is flat without it,
and I didn't see an easy way to share the optimizer's `recursive-kinds` with `instantiate.rkt`
- - -
Improve the static contract optimizer's ability to recognize flat contracts:
1. get the kind of all recursive, named contracts
2. any `name/sc` with `'flat` kind is a flat contract
Step 1 is repeated later in the `instantiate` pass.

static-contracts: improve optimizer's test for flat scs

---

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-test/succeed/sequenceof-integer.rkt

Avoid wrapping 5 when contracted as (Sequenceof Integer).

---

typed-racket-test/succeed/sequenceof-integer.rkt

Tiny change: just add a regression test to make sure `(Sequenceof T)` generates a contract when it should.

add regression test for (Sequenceof T)

---

typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl
typed-racket-lib/typed-racket/typecheck/tc-expression.rkt
typed-racket-lib/typed-racket/types/utils.rkt
typed-racket-lib/typed-racket/utils/utils.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

In addition to potentially being convenient, this helps us not break backwards compatibility when APIs add features that require additional polymorphic variables to properly type.

partial inst

---

typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-apply.rkt
typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-hetero.rkt
typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-list.rkt
typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-special.rkt
typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-values.rkt
typed-racket-lib/typed-racket/typecheck/tc-apply.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

Update the type-table with annotations for some identifiers that are handled specially by `tc-app`.
- - -
Are there any tests for this kind of thing --- for checking whether the `type-table` is updated correctly?
If not, I'll try calling `type-check` directly on some syntax objects, then checking that their components all have annotations.

tc-app: add missing 'function' annotations

---

typed-racket-lib/typed-racket/types/overlap.rkt
typed-racket-test/fail/new-subtype-overlap.rkt

Fix `overlap?` so it recurs into Distinctions (see https://github.com/racket/typed-racket/issues/662).

fix overlap bug for Distinctions

---

typed-racket-lib/typed-racket/rep/rep-utils.rkt

This is an error in the new syntax implementation (racket/racket#1803)

fix invalid reference to nonexisting nested attribute

---

typed-racket-lib/typed-racket/types/resolve.rkt

Make sure `types/resolve.rkt` does not set `current-orig-stx` to `#f`.
Closes #658

bugfix: don't let current-orig-stx be #false

---

typed-racket-lib/typed-racket/utils/opaque-object.rkt

contract combinator
Combined with recent other improvements in racket/contract
(https://github.com/racket/racket/commit/bff0c4113d41ab35d8a7b5f7a4f19c3b453f79f7 and https://github.com/racket/racket/commit/2a1c8a78a59515d9f68bd1f98c1a26dec91ab6bf)
this change is about a 1.4x speedup on configuration 01000
of dungeon and about a 1.3x speedup on configuration 100000000
of acquire

lift some work out ahead of the blame application in the opaque-object

---

rfcs/0000-ignore-type-info.md
typed-racket-lib/typed-racket/private/syntax-properties.rkt
typed-racket-lib/typed-racket/typecheck/tc-expr-unit.rkt

Contains RFC and initial implementation.
[Rendered](https://github.com/samth/typed-racket/blob/ignore-type-info/rfcs/0000-ignore-type-info.md)

Property for forgetting type information.

---

typed-racket-lib/typed-racket/typecheck/check-below.rkt
typed-racket-lib/typed-racket/typecheck/tc-app-helper.rkt
typed-racket-test/succeed/refinements-quicksort.rkt

while writing a version of quicksort w/ refinement types I hit a case where a recursive call to a loop was failing because it could not see that its arguments were well typed... even though it seemed _clear_ that the types were correct.
This change fixed that. However, now going back to the example (which has changed some) I cannot reproduce the error and confirm this fixes it =(
This still seems like a reasonable (i.e. sound, sensible) modification -- but I'm annoyed I don't have a code snippet that breaks without this commit and works with it.
May spend a little more time trying to recreate....

use tc-res when checking args are of correct type

---

rfcs/text/0001-prefab-structs.md

Trying to describe how prefabs _should_ behave.
Currently they act like standard structs, which is unsound (since we cannot guarantee what values will inhabit their fields since they can be created anywhere (i.e. they're prefabs -- anyone can construct them)).
[Rendered](https://github.com/pnwamk/typed-racket/blob/prefab-rfc/rfcs/text/0000-prefab-structs.md)

prefab fix RFC

---

typed-racket-lib/typed-racket/base-env/annotate-classes.rkt
typed-racket-lib/typed-racket/typecheck/check-class-unit.rkt
typed-racket-lib/typed-racket/types/kw-types.rkt
typed-racket-test/succeed/opt-arg-test.rkt
typed-racket-test/unit-tests/keyword-expansion-test.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

Intended as a repair for #710.
The last definition in the updated "opt-arg-test.rkt" does not typecheck in v6.12, but I'm pretty sure it should (as it now does).

repair problems with optional-argument handling

---

typed-racket-lib/typed-racket/static-contracts/optimize.rkt
typed-racket-test/unit-tests/contract-tests.rkt
typed-racket-test/unit-tests/static-contract-instantiate-tests.rkt

Improve the static contract optimizer so a contract like:
```
(or/c struct-predicate-procedure? (-> any/c boolean?))
```
is optimized to a flat contract.
```
(or/c struct-predicate-procedure? (-> any/c any))
```
Closes #712

static-contract: improve `or/sc` optimization

---

typed-racket-compatibility/info.rkt
typed-racket-doc/info.rkt
typed-racket-doc/typed-racket/scribblings/reference/unsafe.scrbl
typed-racket-lib/info.rkt
typed-racket-lib/typed/racket/unsafe.rkt
typed-racket-test/info.rkt
typed-racket-test/succeed/unsafe-reprovide.rkt
typed-racket/info.rkt

Change `unsafe-provide` to un-rename any rename transformers that its asked to provide.
This means one typed module can safely provide some identifiers and, later, another typed module can import those identifier and UNSAFELY provide them.

unsafe-provide: unsafely provide other modules' exports

---

typed-racket-lib/typed-racket/types/type-table.rkt
typed-racket-lib/typed-racket/utils/tc-utils.rkt

Fix the error message for when a string containing format characters
hits the 'type-of' function.
Before: the error was from applying format to a string containing the bad value.
Now: the error reports the bad string
Example program:
```
#lang racket/base
(require typed-racket/types/type-table)
(type-of #'"hello ~e world")
```
Old error:
```
format: format string requires 1 arguments, given 0; arguments were: "no type for hello ~e world 
```
New error:
```
Internal Typechecker Error: no type for "hello ~e world" 
```

fix: improve 'no type' error message for format strings

---

typed-racket-lib/typed-racket/base-env/base-env.rkt

1. Fix incorrect type for `'help-labels` specification
2. Add type for `'usage-help` specification
3. Support optional "help-proc" and "unknown-proc" arguments
4. Use more specific types for "finish-proc" and the flag specs
Closes #692

Fix type of parse-command-line

---

typed-racket-lib/typed-racket/utils/opaque-object.rkt
typed-racket-test/succeed/opaque-object-stronger.rkt

In https://github.com/racket/racket/commit/8ec3edaa9597223f152f5ca12799c8c669e471bb, `contract-equivalent?` was added to `racket/contract` but the methods haven't been implemented yet for typed racket. This commit has some easy ones that happen to make a big difference in the @bennn's gradual typing benchmark suite.

add contract-equivalent to restrict-typed->/c and restrict-typed-field/c

---

typed-racket-lib/typed-racket/typecheck/tc-envops.rkt
typed-racket-lib/typed-racket/types/subtype.rkt
typed-racket-test/succeed/refinements-quicksort.rkt

I was tinkering with refinements yesterday and hit an infinite loop in subtyping and environment extension. Basically the `env+` metafunction recurs when it sees that new info has been derived, and it was getting into a loop where it kept "learning" the same "new" info over and over. These changes fixed it, BUT, I can't find the snippet that was causing the bug >_<.
So... here's the fix... I'll see if I can find the test case again...

avoid infinite looping in subtyping and when extending an environment

---

typed-racket-lib/typed-racket/typecheck/integer-refinements.rkt
typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-main.rkt
typed-racket-lib/typed-racket/typecheck/tc-expr-unit.rkt
typed-racket-test/succeed/refinements-quicksort.rkt

This cleans up and moves the code which adds basic refinements to linear integer arithmetic functions provided by `racket/base` and adds refinements for a few more functions. Instead of having an ever-growing syntax parse clause which each thing we recognize, now we lookup function ids in a free-id-table to see if we have linear refinements for them. This also allows us to quickly determine if a function should be treated like a "dependent function" when we're checking it's arguments -- see changes to `tc-app-main.rkt`.

refactor refinement code, add more basic refinements

---

typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt
typed-racket-lib/typed-racket/types/numeric-tower.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

Fixes https://github.com/racket/typed-racket/issues/747 in the way that is least likely to break any programs (I think).
Basically, any comparison which has a non-trivial negative proposition needs to not include `NaN` in the argument types (since `NaN` in a comparison always produces `#false`).
Still need to add some tests specific to the issue.

fix numeric comparisons for NaN

---

typed-racket-lib/typed-racket/env/type-env-structs.rkt
typed-racket-lib/typed-racket/types/abbrev.rkt
typed-racket-lib/typed-racket/types/numeric-tower.rkt
typed-racket-lib/typed-racket/types/subtype.rkt

Move `extract-props` from 'types/numeric-tower' to 'types/abbrev'. The function was
already provided by 'types/abbrev' and the new location makes more sense
to me.
(History: yesterday I was trying to debug a test failure due to an issue in
'extract-props'. Of course I didn't know 'extract-props' was the problem
at first. It took me 2 hours to figure that out, partly because
'types/numeric-tower' was the last place I expected to look to debug a
problem with vector refinements.)

move 'extract-props' function

---

typed-racket-lib/typed-racket/infer/constraint-structs.rkt
typed-racket-lib/typed-racket/infer/constraints.rkt
typed-racket-lib/typed-racket/infer/infer-unit.rkt
typed-racket-test/unit-tests/infer-tests.rkt

Use a stream to avoid eagerly computing `cset-meet`.
Good news:
- quickly passes the unit test in #743 
- fixes the slowdown for the mutable/immutable vectors PR (see #575 )
Bad news:
- does not fix the _program_ in #743 --- I'll make a note in that issue and work on that program after mutable/immutable vectors are done
- makes typechecking slower overall on the `tr-performance` programs:
```
Compile time ratio (old time = Racket 7.0 release / new time = Racket 7.0.0.10):
schml-specify-rep: 0.97 (i.e. slower, 7.95s (σ 0.06) to 8.21s (σ 0.03))
schml-interp-casts-help: 0.99 (i.e. slower, 17.91s (σ 0.2) to 18.12s (σ 0.11))
parser: 0.92 (i.e. slower, 2.01s (σ 0.01) to 2.19s (σ 0.01))
old-metrics: 0.92 (i.e. slower, 2.37s (σ 0.01) to 2.57s (σ 0.02))
new-metrics: 0.91 (i.e. slower, 3.21s (σ …
```

infer: make `cset-meet` lazy

---

typed-racket-doc/typed-racket/scribblings/reference/libraries.scrbl
typed-racket-more/typed/json.rkt
typed-racket-test/unit-tests/all-tests.rkt
typed-racket-test/unit-tests/json-tests.rkt

Previously, untyped code could use the `json-null` parameter to cause
the functions from `typed/json` not to obey their declared types.
This commit prevents that problem by having the typed wrapper functions
explicitly pass `'null` as the `#:null` argument.
If this approach sees promising, I can add documentation (and probably tests, somewhere?).
Closes https://github.com/racket/typed-racket/issues/768

typed/json: handle json-null

---

typed-racket-lib/typed-racket/env/init-envs.rkt
typed-racket-lib/typed-racket/typecheck/provide-handling.rkt
typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-lib/typed-racket/types/printer.rkt
typed-racket-lib/typed-racket/types/struct-table.rkt
typed-racket-test/succeed/prefab-field-provide.rkt

First attempt at fixing https://github.com/racket/typed-racket/issues/777.
Records which struct field operators are for prefab structs and avoids performing any contract generation for those values (since there is no reasonable protection to be offered beyond what the operator already inherently provides).

do not contract prefab field operators

---

typed-racket-lib/typed-racket/types/printer.rkt
typed-racket-test/unit-tests/type-printer-tests.rkt

Previously the algorithm which tried to tidy-up large union types by covering them with type names in the current environment only considered monomorphic types. This adds support for polymorphic types as well.
e.g., previously hash-set had a very verbose type when printed because the `HashTable` abstraction wasn't considered:
```
> hash-set
- : (All (a b)
(-> (U (Immutable-HashTable a b)
(Mutable-HashTable a b)
(Weak-HashTable a b))
a
b
(Immutable-HashTable a b)))
#<procedure:hash-set>
```
and now it is:
```
> hash-set
- : (All (a b) (-> HashTable a b) a b (Immutable-HashTable a b)))
#<procedure:hash-set>
```
This of course also works for any user-defined types that are polymorphic (yay!).

cover polymorphic types when printing

---

typed-racket-doc/typed-racket/scribblings/reference/types.scrbl

The docs have been behind the implementation for a while---this updates the docs so the two are in sync.

update Sequenceof docs

---

typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-test/succeed/gh-issue-506.rkt

Fix #506 
Note - this change means that the struct name can now be used as a type name. For example, consider `(struct a () #:type-name A)`
**Today:** Only `A` can be used as a type name. A new type named `a` cannot be created (the identifier is already in use.)
**With this change:** Both `A` and `a` can be used as type names to refer to this struct.
If this is a problem, my only idea is to introduce a new lookup table to map `a` to `A`. (There might be a better solution, but I don't know the codebase well enough.)

fix 506: parent structs error when #:type-name is provided

---

typed-racket-doc/typed-racket/scribblings/reference/libraries.scrbl
typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-lib/typed/file/sha1.rkt

Types for `sha1-bytes`, `sha224-bytes`, `sha256-bytes` along with types for `file/sha1` in `typed/file/sha1`.

Add types for new sha functions in v7.1

---

typed-racket-more/typed/net/sendmail.rkt

See [send-mail-message definition](https://docs.racket-lang.org/net/sendmail.html#%28def._%28%28lib._net%2Fsendmail..rkt%29._send-mail-message%29%29).

Fix `send-mail-message` type definition

---

typed-racket-lib/typed-racket/base-env/class-prims.rkt
typed-racket-lib/typed-racket/utils/redirect-contract.rkt
typed-racket-lib/typed-racket/utils/utils.rkt

Two extra calls to `disarm*` allow TR to keep working if some libraries are changed to include `syntax-protect`s (that seem needed).

add some disarms

---

typed-racket-lib/typed-racket/infer/infer-unit.rkt
typed-racket-test/succeed/values-dots-result.rkt
typed-racket-test/unit-tests/infer-tests.rkt

I found this while working on dotted sequence types, but there is a simple case to reproduce:
```
(define #:forall (A ...) (f [v : (List A ... A)])
(apply values v))
(f '(1 2 3))
```
When typechecked as a module form, the last line has expected type `AnyValues`, which ends up in a call `cgen` with types `(Values A ... A)` and `AnyValues`. The former (as an instance of ValuesDots with no non-var prefix) has an empty list of psets, which is joined to form a "null" cset (equal to `no-cset`), which results in a typecheck failure.
This change includes the empty cset in the join so that this case passes even when there are no psets, which seems to me to be the correct behavior.
Incidentally, if the example above is entered into the toplevel REPL instead of as a module, `tc-toplevel-form` passes …

Prevent failure generating constraints for values without psets

---

typed-racket-doc/info.rkt
typed-racket-doc/typed-racket/scribblings/reference/libraries.scrbl
typed-racket-more/info.rkt
typed-racket-more/typed/net/cookies.rkt
typed-racket-more/typed/net/cookies/common.rkt
typed-racket-more/typed/net/cookies/server.rkt
typed-racket-more/typed/web-server/http.rkt

- Weaken the types of `response-output` and
the `#:output` argument to `response/output`
from `Void` to `Any`, corresponding to
<https://github.com/racket/web-server/commit/a93685>
and v1.2 of the `web-server-lib`.
The return type should really be `AnyValues`
to match the contract `any`,
but Typed Racket can't generate a contract for `AnyValues`.
- Update the types for cookie-related functions
to reflect the re-implementation based on `net/cookies/server`
from <https://github.com/racket/web-server/commit/7974d4d>.
This commit adds only as much of `typed/net/cookies/server`
and `typed/net/cookies/common` as needed for `typed/web-server/http`.
- Document that `net/cookie` is deprecated.
- Update the types for `valid-id-cookie?` and `request-id-cookie`
to support the `#:shelf-life` argument …

typed/web-server/http: update types (typed-racket-more v1.10)

---

typed-racket-doc/typed-racket/scribblings/reference/libraries.scrbl

Add `#:link-target? #false` to the second definition of the `Cookie` type.
The goal here is to remove warnings like this from the TR docs:
```
WARNING: collected information for key multiple times: '(index-entry (form ((lib "typed-racket/typed-racket.rkt") Cookie))); values: (list '("Cookie") (list (cached-element (style "RktSym" (list 'tt-chars (css-addition '(collects #"scribble" #"racket.css")) (tex-addition '(collects #"scribble" #"racket.tex")))) "Cookie" ...)) (delayed-index-desc #<procedure:.../manual-bind.rkt:93:3>)) (list '("Cookie") (list (cached-element (style "RktSym" (list 'tt-chars (css-addition '(collects #"scribble" #"racket.css")) (tex-addition '(collects #"scribble" #"racket.tex")))) "Cookie" ...)) (delayed-index-desc #<procedure:.../manual-bind.rkt:93:3>))
```
In a …

doc: remove link from deprecated deftype Cookie

---

typed-racket-lib/typed-racket/static-contracts/instantiate.rkt

The list returned by `hash-keys` is not guaranteed to be parallel to the list returned by a separate call to `hash-values`.
Different orders in Racket Cs cause TR's contract generation to mix up bindings, as illustrated by this "Insert Large Letters" failure:
http://drdr.racket-lang.org/52168/cs/racket/share/pkgs/drracket-test/tests/drracket/insert-large-letters-test.rkt
The contracts shown in the error message will vary, but they're almost always the wrong class contract.

avoid separate `hash-keys` and `hash-values`

---

typed-racket-lib/typed-racket/utils/any-wrap.rkt

See https://github.com/racket/typed-racket/issues/814. Without this PR, the following program fails with `non-chaperone result` errors, but this pull request fixes those errors:
```racket
(struct S ([elems : (Setof Symbol)]) #:transparent)
(cast (ann (S (seteq)) Any) S)
;=> (S (seteq))
(cast (ann (seteq) Any) (Setof Symbol))
;=> (seteq)
```

use chaperone-hash-set to guard sets in any-wrap/c

---

typed-racket-lib/info.rkt

The undeclared dependency causes a problem on racket/racket#2726.
This PR fixes the issue.

Fix undeclared dependency

---

typed-racket-doc/typed-racket/scribblings/reference/libraries.scrbl
typed-racket-more/info.rkt
typed-racket-more/typed/web-server/http.rkt

This commit weakens the type of the message argument
of `response/full`, `response/output`, and `response/xexpr`
from `Bytes` to `(Option Bytes)`.
A `#false` argument causes the message to be inferred from the
numeric response code: note that the type of `response-message`
*does not* change.
Corresponds to v1.4 of the `web-server-lib` package,
https://github.com/racket/web-server/commit/9262724, and
https://github.com/racket/web-server/pull/62.

typed/web-server/http: response message inference (typed-racket-more v1.11)

---

.travis.yml

There was some change in Travis-ci, and the test are failing. I tried with the new recommended method to start `xvfb`, but I got an error in the `integration` test. 
exception-message:  "Gtk initialization failed for display \":99.0\"" 
(See [travis-ci/gus-massa/typed-racket/#L766](https://travis-ci.org/gus-massa/typed-racket/jobs/568025328#L766) )
After some googling ans some random tries, I got this solution, mostly from https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-directly , but I'm not sure about the details.

Fix xvfb in travis-ci

---

.travis.yml
typed-racket-test/fail/async-channel-contract.rkt
typed-racket-test/fail/cast-mod1.rkt
typed-racket-test/fail/cast-mod2.rkt
typed-racket-test/fail/channel-contract.rkt
typed-racket-test/fail/class-contract-1.rkt
typed-racket-test/fail/union-or-exclusive.rkt
typed-racket-test/fail/unit-typed-untyped-1.rkt
typed-racket-test/fail/unit-typed-untyped-2.rkt
typed-racket-test/succeed/cast-mod.rkt
typed-racket-test/succeed/cast-top-level.rkt
typed-racket-test/unit-tests/contract-tests.rkt

Change the names in `check-exn`s to match the new names from cb0fb44

rename contracts in tests

---

typed-racket-lib/typed-racket/private/type-annotation.rkt
typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-special.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

When inferring a second arg. to `make-sequence`, don't check the global
env because the arg might be bound by a for-clause
fixes #849

make-sequence, do not check global env to infer type

---

typed-racket-lib/typed-racket/base-env/base-special-env.rkt

Sync with racket/racket@3907f35d1d.

adapt to `*in-directory` rename as `in-directory` from `racket/private/for`

---

typed-racket-lib/typed-racket/typecheck/tc-expr-unit.rkt
typed-racket-lib/typed-racket/types/kw-types.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

lambdas with optional arguments expand to a
`(let-values (((core) (lambda))) (case-lambda))`
form, which is special-cased in tc-expr-unit. Properties added
to the expansion of typed-lambda (including type var information)
are attached to the whole let-values expression, rather than the
core lambda. To correctly parse type variables in the core lambda,
this patch re-adds the plambda property (if any) when passing it to typecheck.
This fixes #875, https://github.com/racket/racket/issues/1130 and possibly others.

Preserve plambda property when typechecking expanded opt-lambdas

---

typed-racket-more/typed/racket/private/gui-types.rkt

According to the racket/draw documentation, [`find-or-create-brush`][docs] returns a `brush%` or `#f` if the first argument is a string, but always returns a `brush%` if the first argument is a `color%` instead.
The linked docs aren't very clear; according to the above link, `find-or-create-brush` may also always return a `brush%` even if its first argument is a string.
As a side note, the implementation of `find-or-create-brush` [seems to return a black brush][black] if the first argument is a string that isn't recognized as a `color%`. Should the documentation be updated to reflect this or is this intentionally left ambiguous?
[docs]: https://docs.racket-lang.org/draw/brush-list_.html#%28meth._%28%28%28lib._racket%2Fdraw..rkt%29._brush-list~25%29._find-or-create-brush%29%29
[black]: …

Separate types of find-or-create-brush depending on first argument's type

---

typed-racket-lib/typed-racket/rep/type-mask.rkt
typed-racket-lib/typed-racket/rep/type-rep.rkt

Drop `mask:future` since subtyping with future values seems
uncommon.
Related to racket/racket#2925.

Only allow 29 bits of mask size, to support 32-bit Racket CS.

---

typed-racket-doc/info.rkt
typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl
typed-racket-lib/info.rkt
typed-racket-lib/typed-racket/base-env/for-clauses.rkt
typed-racket-lib/typed-racket/base-env/prims.rkt
typed-racket-test/fail/for-result-bad-ann-1.rkt
typed-racket-test/fail/for-result-bad-ann-2.rkt
typed-racket-test/fail/for-result-bad-ann-3.rkt
typed-racket-test/fail/for-result-bad-ann-4.rkt
typed-racket-test/succeed/for-result.rkt
typed-racket/info.rkt

Syntax is the same as untyped racket; the existing optional return type annotation can be used as necessary.
I've updated the documentation and bumped the version number since the API has changed.
Closes issue #872.

Support #:result clause in for/fold and for/list

---

typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl
typed-racket-lib/typed-racket/base-env/prims.rkt
typed-racket-test/succeed/for-last.rkt

This fixes a problem raised about `for/last` and `for*/last` in this thread on the Racket Users List:
https://groups.google.com/d/topic/racket-users/0tOGWZ9O57c/discussion
It uses the existing internal `define-for/acc:-variants` macro to transform
```
(for/last : type (clause ...)
body)
```
into
```
(for/fold ([acc : type #f])
(clause ...)
body)
```
which type-checks in more situations because it assigns a type for `acc` other than `False`.

Improve typechecking for for/last and for*/last

---

typed-racket-doc/typed-racket/scribblings/guide/typed-untyped-interaction.scrbl
typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl

- add a small example to the guide
- edit the reference paragraph on `#:opaque` to:
1. say "opaque" in the first sentence (also using a `deftech`)
2. avoid starting/ending sentences with code
3. add a link to the `define-predicate` section to explain what a predicate is

more docs for #:opaque

---

typed-racket-lib/typed-racket/typecheck/signatures.rkt
typed-racket-lib/typed-racket/typecheck/tc-literal.rkt
typed-racket-test/succeed/pr390-variation-7.rkt

Improve type inference for hash values embedded in syntax objects
- if embedded value is a weak hash, give a `Weak-HashTable` type
- if embedded value is not-immutable and not-weak, give a
`Mutable-HashTable` type

tc-hash: better inference for hashes in syntax objects

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/succeed/index-of.rkt

This PR adds the "index-of" primitive to typed racket. I couldn't find a place to put any test cases; here's the code I would use, though:
``` racket
(require typed/rackunit)
(check-equal? (index-of '(a 12 c d) 'd) 3)
(check-equal? (index-of '(a 12 c d) 'e) #f)
(check-equal? (index-of
'("ab" "cde" "fhgi")
3
(λ ([str : String] [len : Integer])
(= (string-length str) len)))
1)
```

add index-of to base-env.rkt

---

typed-racket-lib/typed-racket/utils/any-wrap.rkt
typed-racket-test/succeed/issue-823.rkt

When wrapping a value,
- keep a seteq of already-seen values
- return if we see the same value twice
~Fixes #823~

any-wrap: avoid looping on cyclic values

---

typed-racket-doc/typed-racket/scribblings/ts-reference.scrbl

Looking at https://docs.racket-lang.org/ts-reference/index.html as of December 22, I see, at the very bottom, below the Index heading, a stray right paren.

Trim excess right paren from ts-reference.scrbl

---

typed-racket-lib/typed-racket/base-env/for-clauses.rkt
typed-racket-lib/typed-racket/base-env/prims.rkt

The original implementation could never work. Also fix `for/vector`.

Fixes to `for` with `#:break` and `#:when` together.

---

typed-racket-doc/typed-racket/scribblings/reference/libraries.scrbl
typed-racket-more/info.rkt
typed-racket-more/typed/web-server/http.rkt

- Add types related to `binding:file/port-in`.
- Strengthen the type of the `#:timeout` arguments to
`valid-id-cookie?` and `request-id-cookie` from `Number` to `Real`,
analogously to <https://github.com/racket/typed-racket/commit/acf7707>.
(A non-real `#:timeout` has always been a runtime error and in one
case was already prohibited by a contract on the untyped side.)
Usually you don't actually want to be using the `#:timeout` argument:
see <https://github.com/racket/web-server/commit/626ad02>.
Related to <https://github.com/racket/web-server/pull/84>.

update typed/web-server/http for v1.6 (typed-racket-more v1.13)

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/fail/regexp-match-pos-star.rkt

Repair output type for `regexp-match-positions*`.

---

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-test/unit-tests/contract-tests.rkt

the old test (not (null? fv)) was always #t because fv is a function,
so `cached-match` never added anything to the cache
- - - 
two questions:
1. any idea how to test this? EDIT: 05dda60 has a test
2. is there a simpler function than `fv` that works here? I noticed `fv` builds a set then converts that to a list ... maybe `(equal? empty-free-vars (free-vars* type))` is better? EDIT: see below, `fv` isn't enough

type-contract: remove sc-cache (was: fix empty cache typo)

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-lib/typed-racket/infer/infer-unit.rkt
typed-racket-lib/typed-racket/infer/signatures.rkt
typed-racket-lib/typed-racket/typecheck/tc-apply.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

add a base type to values for when the number of inputs is unknown
(this type matches the relevant parts of `call-with-values`)
- - -
I found this by looking for ways to reach the 3rd case in `tc/app-apply` here:
https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-apply.rkt#L32
Are there any other examples worth testing?

allow (apply values x) when (: x (Listof _))

---

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-test/unit-tests/contract-tests.rkt

Check for byte-regexp? and avoid using the value as a literal contract

type-contract: fix byte-regexp contract

---

typed-racket-more/typed/pict.rkt
typed-racket-test/succeed/pict.rkt

Currently, `(pict-children (blank 50 50))` = `0`

typed/pict: add missing struct field

---

typed-racket-more/typed/web-server/http.rkt

This is the TR analogue of a proposed change to the
web-server (https://github.com/racket/web-server/pull/85),
in which `web-server/http/empty` goes away, having been
incorporated into `web-server/http/response-structs`.

Change source of web-server's response/empty function

---

typed-racket-lib/typed-racket/utils/any-wrap.rkt
typed-racket-test/unit-tests/contract-tests.rkt

(channel? x) implies (evt? x), so the any-wrap code that protects
channels was never used --- leaving a soundness bug
- move the evt? case below the channel? case
- fix bugs in the channel? chaperone
- - -
Unsoundness example (segfault on 7.6 BC/CS):
```
(require typed/rackunit)
(: ch (Channelof (Pairof Symbol Symbol)))
(define ch (make-channel))
(module u racket/base
(provide f)
(define (f x)
(thread (lambda () (channel-put x 'NotPair)))
(void)))
(require/typed 'u
(f (-> ChannelTop Void)))
(check-exn exn:fail:contract?
(lambda ()
(f ch)
(cdr (channel-get ch))))
```

any-wrap: move channel? case before evt? case

---

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-test/succeed/hashtabletop-flat-contract.rkt
typed-racket-test/succeed/vectortop-flat-contract.rkt

- casts to HashTableTop still work b/c they happen in typed code,
- but untyped code gets an Any-wrapped value
closes a soundness bug

type-contract: add (only-untyped ....) to HashTableTop contract

---

typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-lambda.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

Register a type for the anonymous function in a ((lambda ....) ....)
expression after inferring its type from the arguments.
Also add -true-propset to the "golden" types in a few tests.
(The tests pass now, but look uglier.)

tc-app-lambda: register type for ((lambda ....) ...)

---

typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

Only for base exact 0 this is not true, but this will result in an error anyway as for other options

Extend (Real^Natural -> Real) to exponent Integer

---

typed-racket-more/typed/untyped-utils.rkt
typed-racket-test/succeed/pr907-non-relative.rkt
typed-racket-test/succeed/pr907.rkt

Add a ".." to any relative submodule paths.
- - -
Example program (test.rkt):
```
#lang racket/base
;; test.rkt
(module a typed/racket
(define (f (x : (U Symbol String))) : Void (void))
(provide f))
(module b racket/base
(require typed/untyped-utils typed/racket/base)
(require/untyped-contract (submod ".." a) (f (-> Symbol Void)))
(void))
(require 'b)
```
Without adjustment, `require/untyped-contract` expands to an invalid
require. This new require appears in a new submodule but points to
the same path `(submod ".." a)`, which is not the same goal.
The old error message is:
```
syntax-local-module-exports: unknown module
module name: #<resolved-module-path:(submod 'test[7305] b a)>
```

require/untyped-contract: adjust for relative submod path

---

typed-racket-lib/typed-racket/base-env/prims-contract.rkt

This fixes the last incorrect path in `Typed_Units.html`.
Related to racket/racket#1150.

Provide a proper syntax location for `require-typed-signature`.

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-more/typed/private/framework-types.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

- Correct the method names that were "not found".
See also racket/gui#185
- Add unsafe-fxvector-length and unsafe-fxvector-ref
so that in-fxvector in the for form works correctly.
Add corresponding tests.
Thanks to James Cooper who reported the issue in Slack.

Fix <method not found> and in-fxvector in for form

---

typed-racket-test/fail/support-test-submodule.rkt
typed-racket-test/places.rkt

Looks like this [test](https://github.com/racket/typed-racket/blob/master/typed-racket-test/succeed/submodules.rkt) has not properly run for a while ...

support test submodule in integrated tests

---

typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt
typed-racket-test/succeed/gh-issue-764.rkt

The culprit in issue #764 is [two lines](https://github.com/racket/typed-racket/blob/e03fd8884ed3c512dbac168c240d96816a42b4c3/typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt#L757-L758) specifying type signatures for `=`.
```
(-> -Real -RealZero B : (-PS (-is-type 0 -RealZeroNoNan) (-not-type 0 -RealZeroNoNan)))
(-> -RealZero -Real B : (-PS (-is-type 1 -RealZeroNoNan) (-not-type 1 -RealZeroNoNan)))
```
Replace those two lines with:
(commutative-equality/strict-prop -Real -RealZeroNoNan)
Since the second type does not contain `NaN`, if a real does not equal 
any one of the zeros in the second type (they are all actually equal), then it is not in that type.
Some type information like this is necessary for the type inference
engine to understand that downward induction terminates …

simple fix for issue #764 bad typing of NaN equals

---

typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl

Reading issue #862, I wondered how someone got the idea that you could use a rest argument without a `.` in front of it. According to [the grammar in the reference](https://docs.racket-lang.org/ts-reference/special-forms.html?q=-%3E#%28form._%28%28lib._typed-racket%2Fbase-env%2Fprims..rkt%29._lambda%29%29), rest has to be preceded by a`.` and if it is annotated by a type, the type must be bracketed in the usual way.
I noticed that some existing examples don't do that, so I fixed them.
I also changed a non-list use of a variable named `rest` to the name `second`.  
The fact that they are accepted by the compiler is somebody else's issue. :)

make usage of rest arguments consistent with grammar. minor edits.

---

typed-racket-lib/typed-racket/typecheck/tc-app-helper.rkt
typed-racket-test/fail/gh-issue-944.rkt

Certain type errors with rest arguments lacked a space in their output, making them confusing for beginners. (What is the type `StringString`?)

fix issue #944 by adding an appropriate space in error message

---

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-test/unit-tests/contract-tests.rkt

Check for proper list types and output a matching static contract,
instead of using cons/sc for all kinds of pairs
- - -
Looks like we never make `list/sc` contracts currently --- even though there are sc-optimizer cases for them.

type-contract: look for lists, make list/sc

---

typed-racket-lib/typed-racket/base-env/extra-env-lang.rkt
typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-test/succeed/type-environment.rkt

Let `type-environment` accept the struct #:kernel-maker option,
and pass it on to `d-s`.
Without this option, type-environment does not register a type for
a struct constructor.
Also, delete some comments that have been replaced by contracts.

type-environment: optionally provide struct constructor

---

typed-racket-lib/typed-racket/optimizer/float-complex.rkt
typed-racket-test/succeed/pr950-magnitude.rkt

Bring in line with main racket:
https://docs.racket-lang.org/reference/generic-numbers.html?q=magnitude#%28def._%28%28quote._~23~25kernel%29._magnitude%29%29
stating that inf takes precedence.

magnitude of Float-Complex where one (or both) parts are inf

---

typed-racket-more/typed/openssl.rkt

The optional server protocol parameter type is missing from ssl-listen, as seen here: https://docs.racket-lang.org/openssl/index.html?q=typed%2Fopenssl#%28def._%28%28lib._openssl%2Fmain..rkt%29._ssl-listen%29%29
This updates the type declaration.

fix: Add server protocol to ssl-listen

---

typed-racket-lib/typed-racket/optimizer/vector.rkt
typed-racket-test/optimizer/tests/known-length-vector-op.rkt

```
(define x 0)
(vector-ref (vector (set! x (+ x 1))) 0)
x
```
This program yields 2 currently.

fix duplicated evaluation of vector-expr after optimizing known-length vector-op

---

typed-racket-more/typed/racket/private/gui-types.rkt

Fixes #978 by adding the method types `get-area-selectable` and `set-area-selectable` to the `Pasteboard%` class type.

add Pasteboard% {get,set}-area-selectable

---

typed-racket-lib/typed-racket/types/subtype.rkt
typed-racket-test/succeed/gh-issue-973.rkt

only turn a paramter into a function when the other type is also a function
closes #973

fix a bug in comparing a parameter and a function

---

typed-racket-lib/typed-racket/base-env/base-special-env.rkt

The function was introduced in racket @ 18ff816358f400908b8cdc1071f3f65059da68e3
(This patch should also fix current CI runs, e.g. https://travis-ci.org/github/racket/typed-racket/jobs/741668313)

add types to unsafe-normalize-inputs in racket/private/for

---

typed-racket-lib/typed-racket/base-env/prims.rkt
typed-racket-lib/typed-racket/private/syntax-properties.rkt
typed-racket-lib/typed-racket/typecheck/tc-lambda-unit.rkt
typed-racket-test/succeed/gh-issue-940.rkt

Optional or keyword lambdas is expanded to more lambdas where
syntax objects for the original paramaters are reused. This is problematic when
those parameters are typed with bound type variables in polymorphic functions,
because in generated lambdas those variables would become unbound.
This patch fixes the problem by throwing the types away before typechecking
the generated lambdas.
closes #940

remove type anns for parameters in λs generated from kw/opt plambdas 

---

typed-racket-lib/typed-racket/base-env/prims.rkt

test code(`test.rkt`):
```rkt
(define a b c)
```
origin:
```
/Applications/Racket v7.9/share/pkgs/typed-racket-lib/typed-racket/base-env/prims.rkt:750:10: define: bad syntax (multiple expressions after identifier)
```
now:
```
test.rkt:3:0: define: bad syntax (multiple expressions after identifier)
```
close #813

add missing syntax locations in bad define

---

typed-racket-lib/typed-racket/base-env/base-special-env.rkt

This change saves about 70 ms from following command on my machine (about 430ms to 360ms):
```
racket -e "(require typed-racket/standard-inits) (time (do-standard-inits))"
```

change make-template-identifier implementation to syntax-binding-set

---

typed-racket-lib/typed-racket/typecheck/check-class-unit.rkt
typed-racket-test/succeed/gh-issue-1020.rkt
typed-racket-test/unit-tests/class-tests.rkt

Previously, when `core-method` was used #:declared, it would be recursively
called in patterns even for an unmatched syntax object. Since `core-method`
contained stateful operations (register-self/method), the typechecker could
mistakenly recognize some lambda forms as methods and register wrong parameters
as `self` (see Issue #1020).
closes #1020

fix how and where `core-method` is used within itself.

---

typed-racket-lib/typed-racket/typecheck/tc-lambda-unit.rkt
typed-racket-test/fail/gh-issue-1011.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

When using an expected arrow type to check a lambda with not every parameter
annotated, the existing annotation was thrown away, and the lambda was treated
as non-annotated one.
closes #1011

fix a bug in typechecking partially type-annotated lambdas

---

typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl

To define sub-struct by `define-struct`, following codes fail:
```
(define-struct struct1 ([v1 : Number]) #:type-name Struct1)
(define-struct struct2 struct1 ([v2 : Symbol]) #:type-name Struct2)
(define-struct (T) struct3 struct2 ([v3 : T]) #:type-name Struct3)
```
Error message:
```
define-struct: bad syntax
in: (define-struct struct2 struct1 ((v2 : Symbol)) #:type-name Struct2)
```
It works if we put `name-id` and `parent` in parentheses.
```
(define-struct struct1 ([v1 : Number]) #:type-name Struct1)
(define-struct (struct2 struct1) ([v2 : Symbol]) #:type-name Struct2)
(define-struct (T) (struct3 struct2) ([v3 : T]) #:type-name Struct3)
```

Fix `define-struct` description in Reference.

---

typed-racket-lib/typed-racket/typecheck/signatures.rkt
typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-list.rkt
typed-racket-lib/typed-racket/typecheck/tc-expr-unit.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

improves error reporting for `(list ....)`

---

typed-racket-test/fail/pr13289.rkt
typed-racket-test/optimizer/run.rkt
typed-racket-test/succeed/simple-kw-app.rkt

The following 3 test fail (for me) on windows:
- [fail/pr13289.rkt](https://github.com/racket/typed-racket/blob/master/typed-racket-test/fail/pr13289.rkt)
- [optimizer/test/known-length-vector-op.rkt](https://github.com/racket/typed-racket/blob/master/typed-racket-test/optimizer/tests/known-length-vector-op.rkt)
- [succeed/simple-kw-ap.rkt](https://github.com/racket/typed-racket/blob/master/typed-racket-test/succeed/simple-kw-app.rkt)
This PR solves this. But at least for the third test, I'm not convinced my approach is the best solution. The title of the test suggests what is being tested is kw-app but it uses the file system. So maybe a better approach is to use a kw function that doesn't need the filesystem. Or if it is the filesystem being tested, use a file from the typed-racket-test …

update some tests to pass on windows.

---

typed-racket-lib/typed-racket/base-env/base-special-env.rkt
typed-racket-test/succeed/pr953-in-xvector.rkt

add type for the optional arguments of 'in-fx/fl/extflvector' as in 'in-vector'

type for the optional arguments of 'in-fx/fl/extflvector'

---

typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt
typed-racket-test/succeed/gh-issue-1039.rkt
typed-racket-test/tr-random-testing.rkt

use the same spec to generate types for them.
closes #1039

Unify types for quotient, remainder and quotient/remainder

---

.github/workflows/ci.yml

This commit installs Racket locally in `$HOME`. As a result, the `sudo` uses in the CI can be removed and the default scope can be set to `installation`.

Install Racket locally

---

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/types/printer.rkt
typed-racket-test/fail/gh-issue-1041.rkt
typed-racket-test/succeed/gh-issue-906.rkt

A recursively defined prefab type caused the expansion to diverge.
The changes fix this issue.
closes #906
also make type error for prefab types more comprehensible
closes #1041

Fix a bug in generating contracts for prefabs.

---

typed-racket-lib/typed-racket/types/subtype.rkt
typed-racket-test/succeed/structs-has-subtype.rkt

a struct descriptor associcated with a property name should be a valid argument
to its property accessor

fix subtyping between struct descriptor types & has-struct-property

---

.github/workflows/ci.yml
typed-racket-test/main.rkt

Potentially some changes to TR would require math to be built again.
so we don't need to run any integrated tests that depends on math before `raco
setup math`

make the CI happy

---

typed-racket-doc/typed-racket/scribblings/guide/caveats.scrbl

Add a match example with an annotation and ...
Document how type annotations help the expanded code for match type check.

Adding typing to match when (? number? c) is involved

---

typed-racket-doc/typed-racket/scribblings/guide/occurrence.scrbl

Per email, an example in the TR Guide using a positive proposition.

add guide example of positive proposition

---

typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl
typed-racket-lib/typed-racket/base-env/prims-struct.rkt
typed-racket-lib/typed-racket/env/init-envs.rkt
typed-racket-lib/typed-racket/env/struct-name-env.rkt
typed-racket-lib/typed-racket/typecheck/def-binding.rkt
typed-racket-lib/typed-racket/typecheck/internal-forms.rkt
typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt
typed-racket-lib/typed-racket/utils/struct-info.rkt
typed-racket-test/fail/exported-struct-id-not-type.rkt
typed-racket-test/fail/gh-issue-1050.rkt
typed-racket-test/fail/struct-id-not-type.rkt
typed-racket-test/fail/struct-type-name-not-constr.rkt
typed-racket-test/succeed/gh-issue-506.rkt
typed-racket-test/succeed/struct-constructors.rkt
typed-racket-test/succeed/struct-inheritance-through-exported-macro.rkt
typed-racket-test/succeed/struct-out-with-exported-type-name.rkt

1. fix a bug where struct-out is used with an imported type name
2. implement the design intent that the structure name is not allowed to be used
for the type name,when the latter is provided through #:type-name
3. update the documentation

improve handling for structures 

---

typed-racket-lib/typed-racket/typecheck/def-binding.rkt
typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-test/succeed/struct-constructors.rkt

1. fix a bug where the construct-name wasn't contracted.
2. fix a bug where the struct info was created with the struct name instead of
the extra constructor name when it was supplied

fix struct-related bugs:

---

typed-racket-lib/typed-racket/typecheck/def-binding.rkt
typed-racket-lib/typed-racket/typecheck/internal-forms.rkt
typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt
typed-racket-test/succeed/gh-issue-1088.rkt

Using the constructor name from the struct info to decide whether a struct name
can be used as its constructor is problematic, because in that case the
constructor name is the extra constructor name when the latter is
supplied. Instead, we should pass the constructor name from (define-) struct
forms directly.
This is also a spinoff bugfix from #1078.
These changes include small fixes for `define-struct/exec`
closes #1088

bugfix for struct-related names cont'd:

---

typed-racket-lib/typed-racket/base-env/class-prims.rkt
typed-racket-test/fail/class-define-srcloc.rkt

Update the source location of `define/override`, `define/augment`, etc., for classes. Fixes #1093.
Instead of putting the source location on `begin`, place it on the `define` form.

Update the source location of define/X for classes.

---

typed-racket-more/typed/racket/private/gui-types.rkt
typed-racket-test/gui/succeed/require-typed-gui-class.rkt

These are the methods required for
```
(require/typed racket/gui/base [editor-canvas% Editor-Canvas%])
```
to run without any contract errors.

Add missing methods to Editor-Canvas%

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/succeed/log.rkt

Extend type signature of make-log-receiver to allow n-ary logging topics and log levels.  Current type signature supports only a single logging topic.
This change is more restrictive than the documented behavior of the untyped make-log-receiver which allows for defaulting the topic to #f.  
This fix allows for a typical usage of make-log-receiver to properly type check. e.g.
(make-log-receiver (current-logger) 'info #f 'debug 'my/lib/logger)

Fix make-log-receiver type signature.

---

typed-racket-lib/typed-racket/optimizer/unboxed-let.rkt
typed-racket-lib/typed-racket/typecheck/tc-let-unit.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

when there is no bound variables at LHS, i.e.:
(let-values ([() expr]) body) or (letrec-values ([() expr]) body)
refinements from RHS is still propagated to check the body
close #107

improve let(rec)-values handling

---

.github/workflows/ci.yml
typed-racket-more/typed/racket/private/gui-types.rkt
typed-racket-test/gui/succeed/test-tab-augments.rkt
typed-racket-test/main.rkt

Fix https://drdr.racket-lang.org/57520/. 
The ci jobs for #1111 were successful, because `racket -l typed-racket-test --int`or `racket typed-racket-test/main.rkt --int` never ran any tests under "gui/succeed".

Fix a bug in running tests and bugs in #1111

---

typed-racket-doc/typed-racket/scribblings/reference/types.scrbl
typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-lib/typed-racket/private/parse-type.rkt
typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/rep/core-rep.rkt
typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/exist.rkt
typed-racket-lib/typed-racket/typecheck/error-message.rkt
typed-racket-lib/typed-racket/typecheck/tc-app-helper.rkt
typed-racket-lib/typed-racket/typecheck/tc-funapp.rkt
typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-lib/typed-racket/typecheck/tc-subst.rkt
typed-racket-lib/typed-racket/types/base-abbrev.rkt
typed-racket-lib/typed-racket/types/subtype.rkt
typed-racket-lib/typed-racket/types/tc-result.rkt
typed-racket-test/fail/extract-sp-apply-not-self.rkt
typed-racket-test/succeed/extract-sp-apply-self.rkt
typed-racket-test/succeed/structs-has-subtype.rkt
typed-racket-test/succeed/test-spt-typed-untyped.rkt
typed-racket-test/succeed/user-defined-sp.rkt
typed-racket-test/unit-tests/contract-tests.rkt
typed-racket-test/unit-tests/interactive-tests.rkt
typed-racket-test/unit-tests/parse-type-tests.rkt
typed-racket-test/unit-tests/subtype-tests.rkt

In this PR, existential type results are added to better annotate method extraction.
a property accessor previously annotated `(Some (x) (-> (Has-Struct-Property prop) (-> x Number) : x)` is now annotated `(-> (Has-Struct-Property prop) (Some (-> x Number) : #:+ x))`, i.e. the existential quantification has been pushed downward.
-  An existential type `Result` are `Result` with at least one existential quantifier. It has a constructor and destructor, and there is a function `instantiate-result` used to turn de brunji indexes to names in an existential result when the type checker is checking application of a single arrow function. 
- `subresult*` was changed to reason about subtyping between a (-> Self ....) and a (Some (x) (-> x ....) : x), and two existential type results.
- added some …

use existential type results for method extraction

---

typed-racket-lib/typed-racket/rep/rep-utils.rkt

The pattern variable "var" is out of scope inside the definition of the syntax class "var-name"

Out-of-scope pattern variable in syntax class var-name

---

typed-racket-lib/typed-racket/env/init-envs.rkt
typed-racket-lib/typed-racket/env/type-alias-helper.rkt
typed-racket-lib/typed-racket/private/parse-type.rkt
typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/rep/base-type-rep.rkt
typed-racket-lib/typed-racket/rep/core-rep.rkt
typed-racket-lib/typed-racket/rep/object-rep.rkt
typed-racket-lib/typed-racket/rep/rep-utils.rkt
typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/typecheck/check-class-unit.rkt
typed-racket-lib/typed-racket/typecheck/tc-app-helper.rkt
typed-racket-lib/typed-racket/typecheck/tc-expression.rkt
typed-racket-lib/typed-racket/typecheck/tc-funapp.rkt
typed-racket-lib/typed-racket/typecheck/tc-lambda-unit.rkt
typed-racket-lib/typed-racket/types/base-abbrev.rkt
typed-racket-lib/typed-racket/types/path-type.rkt
typed-racket-lib/typed-racket/types/printer.rkt
typed-racket-lib/typed-racket/types/utils.rkt
typed-racket-test/unit-tests/parse-type-tests.rkt
typed-racket-test/unit-tests/type-printer-tests.rkt

1. `#:no-provide` supports parameters
2. add `#:type-binder` to greatly reduce the boilerplate code to write `Poly`, `Some` and all the other binders.

Refactor rep

---

typed-racket-test/main.rkt
typed-racket-test/unit-tests/all-tests.rkt

This changes enabled test files to run on multiple workers(places). Due to the
overhead of loading typed racket and racket, using all available threads/cores
does not alway yield the best performace. It look like the best number of
workers for parallism is four.
For reference, on my ryzen 5850u pro, the unit tests take 18 seconds to run with
the change. By contrast, 36 seconds were needed to finish the unit tests before.
more fine-grained parallelization, i.e. support for running test-cases/suites in
parallel, should be implemented in rackunit,

support running unit-tests in parallel

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/succeed/make-readtable.rkt

This PR fixes the type of `make-readtable`, to match more closely the contract in untyped Racket.
[Untyped `make-readtable`](https://docs.racket-lang.org/reference/readtables.html#%28def._%28%28quote._~23~25kernel%29._make-readtable%29%29) can take `#false` as its readtable parameter, which is currently not permitted by the typed version.
This causes issues when trying to use `make-readtable` with `(current-readtable)`, which has a type of `(U False Read-Table)` and is thus rejected by the type checker.
Even the contract currently in this PR is incorrect, since it doesn't reflect the variadic nature of `make-readtable`.

Update make-readtable type

---

typed-racket-doc/typed-racket/scribblings/reference/legacy.scrbl
typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl
typed-racket-lib/typed-racket/base-env/prims.rkt

When I was testing the indentation of racket-mode (see https://github.com/greghendershott/racket-mode/issues/569), I accidentally discovered that some grammatical forms of `for` and `let` were not introduced in Document. So I sorted out the document and added these forms.
I'd like to know if these forms are legal, or are they unintentionally defined as such and are not recommended for programmers to use? If it’s the latter, feel free to close this PR.

Document: Complement the syntax introduction of some operators.

---

typed-racket-lib/typed-racket/base-env/base-env.rkt

Both `vector-ref` and `hash-ref` can work on the corresponding `Top` type, so I think it is reasonable to make `mcar` and `mcdr` work on `MPairTop`.

Allow `mcar` and `mcdr` to work on `MPairTop`.

---

typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl

`cast` protects the values by two contracts, which is often too much of a performance penalty.  In most cases, `assert`, occurrence typing, or `ann` should be used.
This PR is a follow-up of [this discussion](https://racket.discourse.group/t/managing-cast-performance-penalty/905).

Mention assert and ann in the docs of cast.

---

typed-racket-doc/typed-racket/scribblings/reference/special-forms.scrbl

Fix the wording of the explanation added by https://github.com/racket/typed-racket/pull/1231.

Improve the explanation of cast and of the reference to assert.

---

typed-racket-compatibility/typed-scheme/no-check.rkt
typed-racket-compatibility/typed/scheme/base/no-check.rkt
typed-racket-compatibility/typed/scheme/no-check.rkt
typed-racket-lib/typed/racket/base/no-check.rkt
typed-racket-lib/typed/racket/no-check.rkt

Closes https://github.com/racket/typed-racket/issues/1223.

Let `typed/racket/no-check` export `racket/base` at phase level 1.

---

typed-racket-lib/typed-racket/base-env/base-env-indexing-abs.rkt
typed-racket-lib/typed-racket/base-env/base-env.rkt

I am a little confused when I read code in `base-env-indexing-abs.rkt`.
In the definition of `indexing`, a total of four types are used to represent indexes: `-Integer`, `-Nat`, `-Index` and `index-type` (as `-Integer` in `base-env-indexing.rkt`). And many functions actually use `exact-nonnegative-integer?` to check their arguments, but TR use `index-type` (aka `Integer`) instead of `Natural` (or `Index`) to check them.
I'm not sure why these functions involving index are treated separately in `base-env-indexing-abs.rkt`, in order to be consistent with the types of other functions, I use `index-type` to define the types for these `raise` functions.
Will there be any compatibility problem if I use more precise types instead of `index-type` for all functions in `indexing`? And in addition …

Add types for some raise functions.

---

typed-racket-lib/typed-racket/base-env/base-env.rkt

`length` just returns the length of a list, it should have nothing to do with the type of the list.

Add types for `indexes-of` and `indexes-where`.

---

typed-racket-lib/typed/racket/base/no-check.rkt

Unfortunately this was accidentally done previously, and fixing it
in #1224 unfortunately broke existing code.

Provide everything from `racket` in `typed/racket/base/no-check`.

---

.github/workflows/resyntax.yml

@samth expressed interest in setting up [Resyntax](https://docs.racket-lang.org/resyntax/) on the Typed Racket repository. This pull request adds a github workflow that runs Resyntax on any changed files in a pull request. Resyntax will suggest changes via a github review, [like this](https://github.com/jackfirth/racket-package-resyntax-action/pull/9#pullrequestreview-1019362007). To apply the changes, the pull request author can click the "Commit suggestion" button that shows up in each comment. Suggestions can be ignored freely; the review does not block merges. Here's an example of what a Resyntax suggestion looks like for someone with commit access:
The Resyntax tool and especially the github integration are still in the early phases of development so there are probably several bugs …

Analyze pull requests with Resyntax

---

.github/workflows/resyntax.yml

The current Resyntax workflow runs on `pull_request`, which gives it a github token with **read-only** access when run on pull requests from forks. Using `pull_request_target` instead gives it a read-write token and allows the action to submit pull request reviews for pull requests from forks.

Fix resyntax permissions issue

---

typed-racket-lib/typed-racket/base-env/prims-contract.rkt
typed-racket-lib/typed-racket/typecheck/def-binding.rkt
typed-racket-lib/typed-racket/typecheck/internal-forms.rkt
typed-racket-lib/typed-racket/typecheck/tc-structs.rkt
typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt
typed-racket-test/fail/reexported-require-typed-struct-has-contracts.rkt
typed-racket-test/succeed/gh-issue-837.rkt
typed-racket-test/succeed/require-typed-struct-info.rkt

fix a bug where re-exported struct names via require/typed/provide don't have struct infomation

---

typed-racket-more/typed/racket/draw.rkt
typed-racket-test/succeed/make-font.rkt

add the two keyword args from:
https://github.com/racket/racket/commit/cca0deb3ff5a570c1c3c03ea0983d106492444b7
- - -
Related, the error message for this is rough:
```
make-font.rkt:7:2: Type Checker: could not apply function;
wrong number of arguments provided
expected: 9
given: 11
in: (make-font #:size 1024.0 #:style style #:weight weight #:face font)
make-font.rkt:7:2: Type Checker: type mismatch
expected: (U #<unsafe-undefined> Font-Smoothing)
given: Positive-Float-No-NaN
in: (make-font #:size 1024.0 #:style style #:weight weight #:face font)
make-font.rkt:7:2: Type Checker: type mismatch
expected: (U #<unsafe-undefined> Font-Style)
given: False
in: (make-font #:size 1024.0 #:style style #:weight weight #:face font)
make-font.rkt:7:2: Type Checker: type mismatch
expected: (U …
```

typed/racket/draw: update make-font type

---

typed-racket-lib/typed-racket/types/printer.rkt

Avoid infinite loops printing prefab types.

---

rfcs/text/0004-shallow-optional-semantics.md
typed-racket-test/info.rkt

Don't compile or run code in `typed-racket-test/unit-tests/shallow-rewrite-expansion/`
Also fix RFC number.

Shallow TR: fix drdr errors

---

.github/workflows/resyntax-analyze.yml
.github/workflows/resyntax-submit-review.yml

There are two issues with the current workflows: the artifact upload step produces malformed JSON, and the artifact download step doesn't work because the action I'm using for it doesn't support downloading artifacts uploaded by other workflows. This pull request should hopefully fix both issues.

Fix Resyntax workflows

---

.github/workflows/resyntax-submit-review.yml

I put this bit in the wrong spot, but after reading the docs it shouldn't be necessary in the first place.

Fix resyntax permissions

---

.github/workflows/resyntax-submit-review.yml

Looks like Typed Racket defaults to read-only permissions for all actions.

Add missing permissions

---

.github/workflows/ci.yml
typed-racket-lib/typed-racket/utils/utils.rkt
typed-racket-test/with-tr-contracts.rkt

This changes PLT_TR_CONTRACTS so that the legal values are `"true"`, `"false"`, `""`, and unset, and only the first of those choices results in `enable-contracts?` being true. Previously, setting `PLT_TR_CONTRACTS` to any string at all (including explicitly setting it to the empty string) would enable contracts.
I made this change so I could simplify the CI setup a little, since this lets the `${{ matrix.enable-contracts }}` expression be passed directly in the environment.

Make PLT_TR_CONTRACTS easier to toggle in CI

---

.github/workflows/ci.yml

The `racket-version` matrix row is unnecessary since it's only ever set to one value. Also, this change tweaks the job names so that they look a little more readable. The new job names are:
- `CI / Racket BC - Contracts Enabled`
- `CI / Racket BC - Contracts Disabled`
- `CI / Racket CS - Contracts Enabled`
- `CI / Racket CS - Contracts Disabled`

Simplify CI job names and matrix

---

typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-test/unit-tests/static-contract-conversion-tests.rkt

Context:
(Vector T) is implemented as the union of two types. Enforcing the
type with two contracts is inefficient; we want one merged contract.
Same for (HashTable K V), which is implemented as three types.
This commit replaces the old static-contract merging with a type merging.
The problem with static contract merging is that it happens after the "typed-side" optimization kicks in --- which meant that two types with equal components could end up as static contracts with unequal components. This was a huge practical problem in the GTP benchmark `dungeon` ... the fix lowers the runtime for one loop in the worst case down from 30 seconds to 1/2 second.

type-contract: merge vector and hash types earlier

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/succeed/hash-union.rkt

for `hash-union`, `hash-union!` and `hash-intersect`
See also: https://racket.discourse.group/t/type-checker-inference-for-polymorphic-keyword-functions-not-supported/145/5
maybe related: following failing test was recently added but I think the first hash should be `#hash()`. However I could be wrong about what is being tested
https://github.com/racket/typed-racket/blob/20acc4bc64907ccf0638c275dccec48461749979/typed-racket-test/fail/hash-union.rkt#L3

Allow #:combine and #:combine/key

---

typed-racket-lib/typed-racket/private/parse-type.rkt
typed-racket-test/succeed/dependent-function-type-thunk-prop.rkt

Dependent function types with no arguments allow more expressive propositions than normal function types.
Error message without this change:
```
<pkgs>/typed-racket-test/succeed/dependent-function-type-thunk-prop.rkt:3:22: ->: expected the identifier `:'
at: Boolean
in: (-> () Boolean #:+ (: v Number) #:- (! v Number))
parsing context: 
while parsing colon^
term: Boolean
location: <pkgs>/typed-racket-test/succeed/dependent-function-type-thunk-prop.rkt:3:29
#(69 7)
```

Allow dependent function types with no arguments

---

typed-racket-more/typed/net/head.rkt

Solution 2 for the previous message.
Fixes up a bunch of the types in this libarary. Just read the code lol.
---
_old message_:
Solution 1 for https://github.com/racket/typed-racket/issues/1285
Upsides:
- Fixes the problem
Downsides:
- `extract-field` remains inconsistent compared to the rest of the `net/head` exports.

Repair `net/head` types.

---

typed-racket-lib/typed-racket/utils/shallow-utils.rkt

Fix the slowdown reported in https://github.com/racket/typed-racket/issues/1293
Saves about 600 seconds on my machine on this command:
```
rm compiled */compiled
time raco make -j 8 cmdline.rkt
```
- Before = `861s`
- After = `250s`

avoid calling normalize-type outside of shallow tr

---

typed-racket-lib/info.rkt
typed-racket-lib/typed-racket/base-env/base-env.rkt

Functions like `open-output-file` have a new optional keyword argument.

update for `open-output-file`, etc., and `#:replace-permissions?`

---

typed-racket-lib/info.rkt
typed-racket-lib/typed-racket/env/signature-helper.rkt
typed-racket-lib/typed-racket/typecheck/check-unit-unit.rkt

This PR updates the way Typed Racket typechecks `unit-from-context` forms to support racket/racket#4567. It should not be merged until that PR is merged, so I’ve marked it a draft for now.
(This branch also includes PR #1303, since it is necessary for it to work. If this PR is merged before that one is, then #1303 can be closed.)

Update `unit-from-context` typechecking strategy

---

.github/workflows/ci.yml
.github/workflows/resyntax-analyze.yml
typed-racket-test/fail/unit-typed-untyped-2.rkt

Update `checkout` to v3 and `setup-racket` to v1.9.1.
- `checkout`: the runtime of v2 is deprecated (racket/racket#4564)
- `setup-racket`: UUtah's URL has changed (Bogdanp/setup-racket#62)

Bump workflow version for runtime & URL updates

---

typed-racket-doc/typed-racket/scribblings/reference/optimization.scrbl
typed-racket-lib/typed-racket/static-contracts/instantiate.rkt

Add a switch to turn off contract optimization.
(SCV-CR needs to disable the optimizations to do its analysis, and people like Shriram might want to show the full contracts for teaching)
This switch _could_ piggyback on the `PLT_TR_NO_OPTIMIZE` / `#:no-optimize` flag, but then code that needs to disable those expression-level optimizations for safety is going to be slower than it needs to be at boundaries. So, it seems better to make a new switch.

add flag to disable static contract optimization

---

typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt
typed-racket-test/unit-tests/shallow-rewrite-expansion/base-env-numeric.rkt
typed-racket-test/unit-tests/shallow-rewrite-expansion/main.rkt

add the default "trust fn result" flag to the definitions at the top of base-env-numeric
thanks @shawnw for the report:
<https://www.reddit.com/r/Racket/comments/11dqjbb/experimenting_with_the_new_typed_racket_modes/?utm_source=share&utm_medium=web2x&context=3>

shallow: stop checking output of base numeric fns

---

typed-racket-lib/typed-racket/base-env/prims-contract.rkt

Replace `#f` with a name in TR's `cast`.
I'm not sure what name to use, but anything seems better than `#f`! The current name is inspired by require/typed's `(interface for _)` names.
cc @mfelleisen who discovered that running the contract profiler on code like this gave confusing output:
```
(define-type Fighter Integer)
(define-type Pill Integer)
(struct interactive [{whose-turn : Symbol} {state : State}] #:prefab #:type-name Interactive)
(struct state [{fighters : [Listof Fighter]} {pills : {Listof Pill}}] #:prefab #:type-name State)
(define mk-state
(let ((ff 0) (pp 0))
(lambda ()
(state
(begin0 (list ff) (set! ff (+ 1 ff)))
(begin0 (list pp) (set! pp (+ 1 pp)))))))
(define mk-interactive
(let ((ww 'who))
(lambda ()
(interactive
ww
(mk-state)))))
(define NN (expt 10 …
```

cast: add value-name

---

typed-racket-more/typed/json.rkt

The `#:indent` keyword was recently introduced to the `write-json` procedure in the main Racket repository[0]. This commit introduces the keyword's corresponding types into the Typed Racket exports.
[0] https://github.com/racket/racket/pull/4686

Add `#:indent` types for `write-json` procedure

---

typed-racket-lib/typed-racket/typecheck/find-annotation.rkt

The function should be able to handle multi expressions in a let body
Fixed drdr R64203 and others.
The problem was revealed by
https://github.com/racket/racket/commit/b8dbadec94ebc4ed30521b64f993398bf1399754, which introduces a (%app void) in the body of expanded code.

repair for find-annotation

---

typed-racket-doc/typed-racket/scribblings/guide/types.scrbl

When I was learning Typed Racket, I was confused by this section of the guide, which gives an example of defining a polymorphic data type. The example used is an optional type called `Opt`, defined analogously to `Maybe` in Haskell. Personally, this example was confusing to me since I then thought the the [Option](https://docs.racket-lang.org/ts-reference/type-ref.html#%28form._%28%28lib._typed-racket%2Fbase-env%2Fbase-types..rkt%29._.Option%29%29) type provided by the standard library was defined in the same way. However, that `(Option t)` type is actually defined as either `t` or `#f`, which aligns better with Racket conventions.
To avoid this confusion, and since `Maybe` from Haskell is already mentioned here, I recommend changing the name of `Opt` to `Maybe` in this example.  I also …

[Docs] Rename Opt to Maybe in guide

---

typed-racket-doc/typed-racket/scribblings/guide/occurrence.scrbl

Section 5.2 of the guide describes how Typed Racket narrows types with propositions. However, I don't think this section makes it clear if and how users can define their own propositions from predicates. In 5.2, the proposition for the built-in type predicate `string?` is discussed. Then, in 5.2.1, it jumps to defining custom one-sided propositions, a slightly more advanced concept. I think it could use a section in between that makes it explicit how to create a proposition from a predicate.
Personally, I ran into this issue when I was learning Typed Racket: at the time I didn't understand from the guide how to define my own proposition. [I asked a question](https://stackoverflow.com/questions/69694263/how-to-assert-listof-string-predicate-in-typed-racket) on StackOverflow and got an …

[Docs] Add section on custom propositions

---

typed-racket-lib/info.rkt
typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-test/fail/match-hash-pattern.rkt
typed-racket-test/succeed/match-hash-pattern.rkt

base-env: add support for hash patterns in match

---

typed-racket-doc/typed-racket/scribblings/reference/types.scrbl
typed-racket-lib/typed-racket/base-env/base-types-extra.rkt
typed-racket-lib/typed-racket/base-env/base-types.rkt
typed-racket-test/succeed/unicode-aliases.rkt

- Added `∪` as an alias for `U`.
- Added `→*` as an alias for `->*`.

Add Unicode Aliases for `U` and `->*`.

---

typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-list.rkt

This addresses a regression in commit 8d9cb49.
That commit uses (when (andmap not errs) (expected-but-got ...)) to suppress some errors when type-checking list elements. Before this, there would be two errors reported: one for the list element itself and one for the surrounding list. However, as per #1379 this change suppressed too much. In certain cases it wouldn't report any errors for an invalid list.
I couldn't figure out a way to report errors perfectly, so instead, I decided to revert the relevant change in 8d9cb49. This means list could report multiple errors again, but it's honestly not that bad. It shows the innermost location where the problem happened, as well as the wider context of the list, which can be helpful for locating and understanding the error. An example using the …

Fix type-checking list elements

---

typed-racket-doc/typed-racket/scribblings/reference/types.scrbl

This PR updates the documentation for `Sequenceof` to indicate that it can be used without any type variable.

doc: clarify that `(Sequenceof)` is valid

---

typed-racket-more/typed/xml.rkt
typed-racket-test/unit-tests/xml-tests.rkt

Checklist
See also: Issue #1415 
In (untyped) racket, the XML collection uses a `source` struct whose fields `start` and `stop` follow the contract `location/c`. The `location/c` contract is defined as follows:
(or/c location? symbol? #f)
However, in typed/racket the aforementioned fields are typed as `Location` which represents only the struct but neither symbols nor false.
This pull request extends the typing of `source`'s `start` and `stop` to entail both symbols and false typing them as
(U Location Symbol False)

Fix correspondence between location/c and Location in typed/racket

---

typed-racket-doc/typed-racket/scribblings/reference/types.scrbl
typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-lib/typed-racket/base-env/base-types.rkt
typed-racket-lib/typed-racket/env/init-envs.rkt
typed-racket-lib/typed-racket/infer/infer-unit.rkt
typed-racket-lib/typed-racket/private/type-contract.rkt
typed-racket-lib/typed-racket/rep/type-mask.rkt
typed-racket-lib/typed-racket/rep/type-rep.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/derived.rkt
typed-racket-lib/typed-racket/static-contracts/combinators/structural.rkt
typed-racket-lib/typed-racket/types/abbrev.rkt
typed-racket-lib/typed-racket/types/printer.rkt
typed-racket-lib/typed-racket/types/subtype.rkt
typed-racket-test/succeed/treelist-contract.rkt
typed-racket-test/succeed/treelist.rkt
typed-racket-test/unit-tests/subtype-tests.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

Added TreeList as a type corresponding to the data structure provided by racket/treelist. The only support currently is for Immutable TreeLists. Types were provided for all immutable Treelist functions as described in Section 4.16 of The Racket Reference, with the exception of for/treelist and for*/treelist, as no other similar structures (i.e. sets) supported typings for their respective "for/" functions. Functions treelist-append* and treelist-flatten return some undesirable/inelegant types, but I do not know how to add a proper level of specificity. Tests for all supported functions are provided in typed-racket-test/unit-tests/typecheck-tests.rkt.

Added TreeLists to Typed-Racket along with type-checking tests.

---

typed-racket-more/typed/xml/plist.rkt

The function `write-plist` has been typed
(-> Plist-Dict Output-Port Void)
However, the untyped version has a less restrictive contract on the first argument:
(plist-value? output-port? . -> . void?)
This pr relaxes the type of the first argument to Plist-Value, thus being
(-> Plist-Value Output-Port Void)

improve type definition of write-plist

---

.github/workflows/ci.yml

Racket BC is no longer built in snapshots, so don't try to use those in CI.

Drop BC CI testing

---

typed-racket-lib/typed-racket/base-env/base-env.rkt
typed-racket-lib/typed-racket/rep/rep-utils.rkt
typed-racket-lib/typed-racket/typecheck/signatures.rkt
typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-lambda.rkt
typed-racket-lib/typed-racket/typecheck/tc-lambda-unit.rkt
typed-racket-test/succeed/events-with-async-channel.rkt
typed-racket-test/succeed/events.rkt
typed-racket-test/unit-tests/typecheck-tests.rkt

This does not apply an expected type to the actual function body,
it just gives a type to the function when referred to recursively.
This addresses a problem with inference for let loop in lambda as
the argument to `thread` now that `thread` is a keyword function and
therefore lifts its arguments to a `let` ahead of the function.
Fixing the relevant problem also requires improving the type of `thread`.

Propagate a trivial expected type for recursive lambda if neccessary
